// This file is generated by FBC.

#ifndef _CORE022_H_
#define _CORE022_H_

#include "fbtypes.h"
#include "Gen.h"
#include "Pass10.h"
#include "Print.h"

typedef struct {
    Gen g;
    Pass10 p1;
    Pass10 p2;
    Print pr;
} _Core022;

/* Function block initialization function */
void _Core022init(_Core022* me);

/* Function block execution function */
void _Core022run(_Core022* me);

#endif // _CORE022_H_
