// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Composite Function Block for _Core0
#include "_Core0.h"

//When running a composite block, note that you would call the functions in this order
//_init(); 
//do {
//_syncEvents();
//_syncData();
//_run();
//} loop;


/* _Core0_preinit() is required to be called to 
 * initialise an instance of _Core0. 
 * It sets all I/O values to zero.
 */
int _Core0_preinit(struct _Core0 *me) {
	//if there are input events, reset them
	
	//if there are output events, reset them
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(ArgoRx_preinit(&me->saw1rx) != 0) {
		return 1;
	}
	if(ArgoRx_preinit(&me->saw2rx) != 0) {
		return 1;
	}
	if(ArgoRx_preinit(&me->saw3rx) != 0) {
		return 1;
	}
	if(PrintStatus_preinit(&me->statusprint) != 0) {
		return 1;
	}
	
	
	//if this is a BFB, set _trigger to be true and start state so that the start state is properly executed
	

	return 0;
}

/* _Core0_init() is required to be called to 
 * set up an instance of _Core0. 
 * It passes around configuration data.
 */
int _Core0_init(struct _Core0 *me) {
	//pass in any parameters on this level
	me->saw1rx.ChanId = 1;
	me->saw2rx.ChanId = 2;
	me->saw3rx.ChanId = 3;
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	me->statusprint.Saw1Status = me->saw1rx.Data;
	me->statusprint.Saw2Status = me->saw2rx.Data;
	me->statusprint.Saw3Status = me->saw3rx.Data;
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(ArgoRx_init(&me->saw1rx) != 0) {
		return 1;
	}
	if(ArgoRx_init(&me->saw2rx) != 0) {
		return 1;
	}
	if(ArgoRx_init(&me->saw3rx) != 0) {
		return 1;
	}
	if(PrintStatus_init(&me->statusprint) != 0) {
		return 1;
	}
	
	

	return 0;
}



/* _Core0_syncEvents() synchronises the events of an
 * instance of _Core0 as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core0_syncEvents(struct _Core0 *me) {
	//for all composite function block children, call this same function
	
	//for all basic function block children, perform their synchronisations explicitly
	//events are always copied
	//inputs that go to children
	
	me->statusprint.inputEvents.event.StatusUpdate = me->saw1rx.outputEvents.event.DataPresent || me->saw2rx.outputEvents.event.DataPresent || me->saw3rx.outputEvents.event.DataPresent; 
	
	//outputs of parent cfb
	
	
}

/* _Core0_syncData() synchronises the data connections of an
 * instance of _Core0 as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core0_syncData(struct _Core0 *me) {
	//for all composite function block children, call this same function
	
	//for all basic function block children, perform their synchronisations explicitly
	//Data is sometimes copied
	
	//sync for saw1rx (of type ArgoRx) which is a BFB
	
	
	//sync for saw2rx (of type ArgoRx) which is a BFB
	
	
	//sync for saw3rx (of type ArgoRx) which is a BFB
	
	
	//sync for statusprint (of type PrintStatus) which is a BFB
	
	if(me->statusprint.inputEvents.event.StatusUpdate == 1) { 
		me->statusprint.Saw1Status = me->saw1rx.Data;
		me->statusprint.Saw2Status = me->saw2rx.Data;
		me->statusprint.Saw3Status = me->saw3rx.Data;
	} 
	
	
	//for data that is sent from child to this CFB (me), always copy (event controlled copies will be resolved at the next level up)
	
	

}


/* _Core0_run() executes a single tick of an
 * instance of _Core0 according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void _Core0_run(struct _Core0 *me) {
	ArgoRx_run(&me->saw1rx);
	ArgoRx_run(&me->saw2rx);
	ArgoRx_run(&me->saw3rx);
	PrintStatus_run(&me->statusprint);
	
}

