// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block PrintStatus
#ifndef PRINTSTATUS_H_
#define PRINTSTATUS_H_

#include "fbtypes.h"

//This is a BFB, so we need an enum type for the state machine
enum PrintStatus_states { STATE_PrintStatus_Start, STATE_PrintStatus_Await_Data };


union PrintStatusInputEvents {
	struct {
		UDINT StatusUpdate : 1;
	} event;
	UDINT events[1];
};


//this block had no output events


struct PrintStatus {
    //input events
	union PrintStatusInputEvents inputEvents;

    //output events
	

    //input vars
	INT Saw1Status;
    INT Saw2Status;
    INT Saw3Status;
    
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum PrintStatus_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
};

//all FBs get a preinit function
int PrintStatus_preinit(struct PrintStatus _SPM *me);

//all FBs get an init function
int PrintStatus_init(struct PrintStatus _SPM *me);

//all FBs get a run function
void PrintStatus_run(struct PrintStatus _SPM *me);

void PrintStatus_DoPrintStatus(struct PrintStatus _SPM *me);


#endif
