// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block SawmillSwitch
#ifndef SAWMILLSWITCH_H_
#define SAWMILLSWITCH_H_

#include "fbtypes.h"

//This is a BFB, so we need an enum type for the state machine
enum SawmillSwitch_states { STATE_SawmillSwitch_Start };


//this block had no input events


union SawmillSwitchOutputEvents {
	struct {
		UDINT ControlChange : 1;
	} event;
	UDINT events[1];
};


struct SawmillSwitch {
    //input events
	

    //output events
	union SawmillSwitchOutputEvents outputEvents;

    //input vars
	
    //output vars
	BOOL Run;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum SawmillSwitch_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
};

//all FBs get a preinit function
int SawmillSwitch_preinit(struct SawmillSwitch *me);

//all FBs get an init function
int SawmillSwitch_init(struct SawmillSwitch *me);

//all FBs get a run function
void SawmillSwitch_run(struct SawmillSwitch _SPM *me);




#endif
