// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block SawmillModule
#ifndef SAWMILLMODULE_H_
#define SAWMILLMODULE_H_

#include "fbtypes.h"

//This is a CFB, so we need the #includes for the child blocks embedded here
#include "SawmillSwitch.h"
#include "SawMotor.h"
#include "SawdustScale.h"
#include "SawmillLaser.h"
#include "SawmillControl.h"


//this block had no input events


union SawmillModuleOutputEvents {
	struct {
		UDINT MessageChange : 1;
	} event;
	UDINT events[1];
};


typedef struct {
    //input events
	

    //output events
	union SawmillModuleOutputEvents outputEvents;

    //input vars
	
    //output vars
	INT Message;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	SawmillSwitch_t runswitch;
	SawMotor_t saw;
	SawdustScale_t scale;
	SawmillLaser_t laser;
	SawmillControl_t control;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
} SawmillModule_t;

//all FBs get a preinit function
int SawmillModule_preinit(SawmillModule_t *me);

//all FBs get an init function
int SawmillModule_init(SawmillModule_t *me);

//all FBs get a run function
void SawmillModule_run(SawmillModule_t *me);

//composite/resource/device FBs get sync functions
void SawmillModule_syncEvents(SawmillModule_t *me);
void SawmillModule_syncData(SawmillModule_t *me);

#endif
