// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block StartGen
#ifndef STARTGEN_H_
#define STARTGEN_H_

#include "fbtypes.h"



//This is a BFB, so we need an enum type for the state machine
enum StartGen_states { STATE_StartGen_Start, STATE_StartGen_setup, STATE_StartGen_emit };


//this block had no input events


union StartGenOutputEvents {
	struct {
		UDINT Start;
	} event;
	
};


typedef struct {
    //input events
	

    //output events
	union StartGenOutputEvents outputEvents;

    //input vars
	LREAL SetDeltaTime;
    
    //output vars
	LREAL DeltaTime;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum StartGen_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	

	
} StartGen_t;

//all FBs get a preinit function
int StartGen_preinit(StartGen_t  *me);

//all FBs get an init function
int StartGen_init(StartGen_t  *me);

//all FBs get a run function
void StartGen_run(StartGen_t  *me);



#endif
