// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block WaterHeaterPlantODE
#ifndef WATERHEATERPLANTODE_H_
#define WATERHEATERPLANTODE_H_

#include "fbtypes.h"


#include "cvode/cvode.h"
#include "nvector/nvector_serial.h"
#include "cvode/cvode_dense.h"
#include "sundials/sundials_dense.h"
#include "sundials/sundials_types.h"


//This is a BFB, so we need an enum type for the state machine
enum WaterHeaterPlantODE_states { STATE_WaterHeaterPlantODE_Start, STATE_WaterHeaterPlantODE_t1_enter_0, STATE_WaterHeaterPlantODE_t1, STATE_WaterHeaterPlantODE_t2_enter_0, STATE_WaterHeaterPlantODE_t2, STATE_WaterHeaterPlantODE_t1_enter_1, STATE_WaterHeaterPlantODE_t4, STATE_WaterHeaterPlantODE_t3_enter_0, STATE_WaterHeaterPlantODE_t3, STATE_WaterHeaterPlantODE_t4_enter_0, STATE_WaterHeaterPlantODE_t2_enter_1, STATE_WaterHeaterPlantODE_t4_enter_1 };


union WaterHeaterPlantODEInputEvents {
	struct {
		UDINT HeatChange;
		UDINT Start;
	} event;
	
};


union WaterHeaterPlantODEOutputEvents {
	struct {
		UDINT Ychange;
	} event;
	
};


typedef struct {
    //input events
	union WaterHeaterPlantODEInputEvents inputEvents;

    //output events
	union WaterHeaterPlantODEOutputEvents outputEvents;

    //input vars
	BOOL Heat;
    LREAL DeltaTime;
    LREAL K;
    LREAL H;
    
    //output vars
	LREAL Y;
    
	//any internal vars (BFBs only)
    LREAL X;
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum WaterHeaterPlantODE_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	//this block uses cvode
	void *cvode_mem;
	N_Vector ode_solution;
	realtype T0;
	realtype Tnext;
	realtype Tcurr;
	int solveInProgress;
	

	
} WaterHeaterPlantODE_t;

//all FBs get a preinit function
int WaterHeaterPlantODE_preinit(WaterHeaterPlantODE_t  *me);

//all FBs get an init function
int WaterHeaterPlantODE_init(WaterHeaterPlantODE_t  *me);

//all FBs get a run function
void WaterHeaterPlantODE_run(WaterHeaterPlantODE_t  *me);



#endif
