-- This file has been automatically generated by go-iec61499-vhdl and should not be edited by hand
-- Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499-vhdl

-- This file represents the Basic Function Block for Conveyor_SIFB

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;



entity Conveyor_SIFB is

	port(
		--for clock and reset signal
		clk		: in	std_logic;
		reset	: in	std_logic;
		enable	: in	std_logic;
		sync	: in	std_logic;
		
		--input events
		conveyor_run_changed_eI : in std_logic := '0';
		
		
		--output events
		conveyor_moving_changed_eO : out std_logic;
		conveyor_jammed_changed_eO : out std_logic;
		
		
		--input variables
		conveyor_run_I : in std_logic := '0'; --type was BOOL
		
		
		--output variables
		conveyor_moving_O : out std_logic; --type was BOOL
		conveyor_jammed_O : out std_logic; --type was BOOL
		
		
		--special emitted internal vars for I/O
		rx_conveyor_moving : in std_logic; --type was BOOL
		rx_conveyor_jammed : in std_logic; --type was BOOL
		tx_conveyor_run : out std_logic; --type was BOOL
		
		--for done signal
		done : out std_logic
	);

end entity;


architecture rtl of Conveyor_SIFB is
	-- Build an enumerated type for the state machine
	type state_type is (STATE_Start);

	-- Register to hold the current state
	signal state   : state_type := STATE_Start;

	-- signals to store variable sampled on enable 
	signal conveyor_run : std_logic := '0'; --register for input
	
	-- signals to rename outputs 
	signal conveyor_moving : std_logic := '0'; 
	signal conveyor_jammed : std_logic := '0'; 
	

	
	--signals to rename output events
	signal conveyor_moving_changed_eO_ecc_out : std_logic := '0'; --used when event driven from ECC (normal FB behaviour)
	signal conveyor_moving_changed_eO_alg_out : std_logic := '0'; --used when event driven from algorithm (normal SIFB behaviour)
	signal conveyor_jammed_changed_eO_ecc_out : std_logic := '0'; --used when event driven from ECC (normal FB behaviour)
	signal conveyor_jammed_changed_eO_alg_out : std_logic := '0'; --used when event driven from algorithm (normal SIFB behaviour)
	

	-- signals for enabling algorithms	
	signal conveyor_sifb_alg_alg_en : std_logic := '0'; 
	signal conveyor_sifb_alg_alg_done : std_logic := '1';
	

	-- signal for algorithm completion
	signal AlgorithmsStart : std_logic := '0';
	signal AlgorithmsDone : std_logic;

	--internal variables 
	signal rx_conveyor_moving_prev : std_logic; --type was BOOL 
	signal rx_conveyor_jammed_prev : std_logic; --type was BOOL 
begin
	-- Registers for data variables (only updated on relevant events)
	process (clk)
	begin
		if rising_edge(clk) then
			if sync = '1' then
				
				if conveyor_run_changed_eI = '1' then
					conveyor_run <= conveyor_run_I;
				end if;
				
			end if;
		end if;
	end process;
	
	--output var renaming, no output registers as inputs are stored where they are processed
	conveyor_moving_O <= conveyor_moving;
	conveyor_jammed_O <= conveyor_jammed;
			
	
	-- Logic to advance to the next state
	process (clk, reset)
	begin
		if reset = '1' then
			state <= STATE_Start;
			AlgorithmsStart <= '1';
		elsif (rising_edge(clk)) then
			if AlgorithmsStart = '1' then --algorithms should be triggered only once via this pulse signal
				AlgorithmsStart <= '0';
			elsif enable = '1' then 
				--default values
				state <= state;
				AlgorithmsStart <= '0';

				--next state logic
				--if AlgorithmsStart = '0' and AlgorithmsDone = '1' then
					case state is
						when STATE_Start =>
							if true then
								state <= STATE_Start;
								AlgorithmsStart <= '1';
							end if;
						
					end case;
				--end if;
			end if;
		end if;
	end process;

	-- Event outputs and internal algorithm triggers depend solely on the current state
	process (state)
	begin
		--default values
		--events
		conveyor_moving_changed_eO_ecc_out <= '0';
		conveyor_jammed_changed_eO_ecc_out <= '0';
		
		--algorithms
		conveyor_sifb_alg_alg_en <= '0'; 

		case state is
			when STATE_Start =>
				conveyor_sifb_alg_alg_en <= '1';
				
			
		end case;
	end process;

	-- Algorithms process
	process(clk)
	begin
		if rising_edge(clk) then
			if AlgorithmsStart = '1' then			
				
				if conveyor_sifb_alg_alg_en = '1' then -- Algorithm conveyor_sifb_alg
					conveyor_sifb_alg_alg_done <= '0';
					
					--logic for resetting algorithm-driven output events
					conveyor_moving_changed_eO_alg_out <= '0';
					conveyor_jammed_changed_eO_alg_out <= '0';
					
				end if;
				
			end if;

			
			if conveyor_sifb_alg_alg_done = '0' then -- Algorithm conveyor_sifb_alg

--begin algorithm raw text
--update previous values
rx_conveyor_moving_prev <= rx_conveyor_moving;
rx_conveyor_jammed_prev <= rx_conveyor_jammed;

--these are what we use to drive events
--conveyor_moving_changed_eO_alg_out;
--conveyor_jammed_changed_eO_alg_out;

if rx_conveyor_moving_prev /= rx_conveyor_moving then
	conveyor_moving_changed_eO_alg_out <= '1';
	conveyor_moving <= rx_conveyor_moving;
end if;

if rx_conveyor_jammed_prev /= rx_conveyor_jammed then
	conveyor_jammed_changed_eO_alg_out <= '1';
	conveyor_jammed <= rx_conveyor_jammed;
end if;

--emit outputs (input is already registered to only update on tick boundary with correct input event)
tx_conveyor_run <= conveyor_run;

conveyor_sifb_alg_alg_done <= '1';
--end algorithm raw text

			end if;
			
		end if;
	end process;

	--Done signal
	AlgorithmsDone <= (not AlgorithmsStart) and (not enable) and conveyor_sifb_alg_alg_done;
	Done <= AlgorithmsDone;

	
	--logic for renamed output events
	conveyor_moving_changed_eO <= conveyor_moving_changed_eO_ecc_out or conveyor_moving_changed_eO_alg_out;
	conveyor_jammed_changed_eO <= conveyor_jammed_changed_eO_ecc_out or conveyor_jammed_changed_eO_alg_out;
	

end rtl;
