// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block Output
#ifndef OUTPUT_H_
#define OUTPUT_H_

#include "fbtypes.h"



//This is a BFB, so we need an enum type for the state machine
enum Output_states { STATE_Output_Start, STATE_Output_p };


union OutputInputEvents {
	struct {
		UDINT output;
	} event;
	
};


//this block had no output events


typedef struct {
    //input events
	union OutputInputEvents inputEvents;

    //output events
	

    //input vars
	LREAL var;
    
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum Output_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	

	
} Output_t;

//all FBs get a preinit function
int Output_preinit(Output_t  *me);

//all FBs get an init function
int Output_init(Output_t  *me);

//all FBs get a run function
void Output_run(Output_t  *me);



#endif
