// This file is generated by FBC.

#ifndef GEN_H_
#define GEN_H_

#include "fbtypes.h"

typedef union {
    struct {
        UDINT CountChanged ; // 
    } event;
} GenOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    GenOEvents _output;
    LINT Count; // 
    LINT _Count;
} Gen;

/* Function block initialization function */
void Geninit(Gen* me);

/* Function block execution function */
void Genrun(Gen* me);

/* ECC algorithms */
void Gen_IncCountService(Gen* me);

#endif // GEN_H_
