// This file is generated by FBC.

#include "_CBCoreSingle.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void _CBCoreSingleinit(_CBCoreSingle* me)
{
    SifbAmmeterinit(&me->amm1);
    SifbTimerinit(&me->timer1);
    CfbBreakerControllerinit(&me->cb1);
    SifbManagementControlsinit(&me->hm1);
    SifbIntLedinit(&me->led1);
    SifbManagementControlsinit(&me->hm3);
    SifbIntLedinit(&me->led3);
    SifbAmmeterinit(&me->amm3);
    CfbBreakerControllerinit(&me->cb3);
    SifbTimerinit(&me->timer3);
    SifbManagementControlsinit(&me->hm2);
    SifbIntLedinit(&me->led2);
    SifbAmmeterinit(&me->amm2);
    CfbBreakerControllerinit(&me->cb2);
    SifbTimerinit(&me->timer2);
    SifbCBPrintStatusinit(&me->print);
}

/* Function block execution function */
void _CBCoreSinglerun(_CBCoreSingle* me)
{
    me->cb1._i_set = me->hm1._i_set;
    me->cb1._input.event.rst = me->hm1._output.event.rst;
    me->cb1._input.event.i_set_change = me->hm1._output.event.i_set_change;
    me->cb1._i = me->amm1._i;
    me->cb1._input.event.tick = me->timer1._output.event.Tick;
    me->cb1._input.event.brk = me->hm1._output.event.brk;
    me->cb1._input.event.i_measured = me->amm1._output.event.i_measured;
    me->led1._i = me->cb1._b;
    me->led1._input.event.i_change = me->cb1._output.event.b_change;
    me->led3._input.event.i_change = me->cb3._output.event.b_change;
    me->led3._i = me->cb3._b;
    me->cb3._input.event.i_measured = me->amm3._output.event.i_measured;
    me->cb3._input.event.rst = me->hm3._output.event.rst;
    me->cb3._input.event.i_set_change = me->hm3._output.event.i_set_change;
    me->cb3._i = me->amm3._i;
    me->cb3._input.event.brk = me->hm3._output.event.brk;
    me->cb3._i_set = me->hm3._i_set;
    me->cb3._input.event.tick = me->timer3._output.event.Tick;
    me->led2._input.event.i_change = me->cb2._output.event.b_change;
    me->led2._i = me->cb2._b;
    me->cb2._i_set = me->hm2._i_set;
    me->cb2._input.event.rst = me->hm2._output.event.rst;
    me->cb2._input.event.i_set_change = me->hm2._output.event.i_set_change;
    me->cb2._i = me->amm2._i;
    me->cb2._input.event.brk = me->hm2._output.event.brk;
    me->cb2._input.event.tick = me->timer2._output.event.Tick;
    me->cb2._input.event.i_measured = me->amm2._output.event.i_measured;
    me->print._input.event.StatusUpdate = me->cb1._output.event.b_change || me->cb3._output.event.b_change || me->cb2._output.event.b_change;
    me->print._St1 = me->cb1._b;
    me->print._St2 = me->cb2._b;
    me->print._St3 = me->cb3._b;
    
    SifbAmmeterrun(&me->amm1);
    SifbTimerrun(&me->timer1);
    CfbBreakerControllerrun(&me->cb1);
    SifbManagementControlsrun(&me->hm1);
    SifbIntLedrun(&me->led1);
    SifbManagementControlsrun(&me->hm3);
    SifbIntLedrun(&me->led3);
    SifbAmmeterrun(&me->amm3);
    CfbBreakerControllerrun(&me->cb3);
    SifbTimerrun(&me->timer3);
    SifbManagementControlsrun(&me->hm2);
    SifbIntLedrun(&me->led2);
    SifbAmmeterrun(&me->amm2);
    CfbBreakerControllerrun(&me->cb2);
    SifbTimerrun(&me->timer2);
    SifbCBPrintStatusrun(&me->print);
    
}
