// This file is generated by FBC.

#include "_CBCoreSingle.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

typedef struct {
} _CBCoreSingleReg;

#ifdef _MSC_VER
#include <windows.h>
#include <time.h>
int gettimeofday(struct timeval* tp, void* tzp)
{ 
    DWORD t;
    t = GetTickCount();
    tp->tv_sec = t / 1000;
    tp->tv_usec = (t % 1000) * 1000; 
    return 0; // 0 indicates that the call succeeded.
}

void timersub( const struct timeval * tvp, const struct timeval * uvp, struct timeval* vvp )
{ 
    vvp->tv_sec = tvp->tv_sec - uvp->tv_sec;
    vvp->tv_usec = tvp->tv_usec - uvp->tv_usec;
    if( vvp->tv_usec < 0 )
    { 
       --vvp->tv_sec;
       vvp->tv_usec += 1000000;
    }
}
#endif // _MSC_VER

int main(int argc, char* argv[])
{
    _CBCoreSingleReg _sysInterface;
    _CBCoreSingle _var;
    memset(&_sysInterface, 0, sizeof(_CBCoreSingleReg));
    memset(&_var, 0, sizeof(_CBCoreSingle));
    _CBCoreSingleinit(&_var);

    for (;;) {
        _CBCoreSinglerun(&_var);
    }

    return 0;
}
