// This file is generated by FBC.

#ifndef BFBIDMTCURVE_H_
#define BFBIDMTCURVE_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT tick : 1; // 
        UDINT i_measured : 1; // 
        UDINT i_set_change : 1; // 
    } event;
} BfbIDMTCurveIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT unsafe : 1; // 
    } event;
} BfbIDMTCurveOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    BfbIDMTCurveIEvents _input;
    REAL i; // 
    REAL _i;
    REAL i_set; // 
    REAL _i_set;
    BfbIDMTCurveOEvents _output;
    ULINT cnt; // 
    LREAL max; // 
    REAL k; // 
    BOOL b; // 
    BOOL a; // 
} BfbIDMTCurve;

/* Function block initialization function */
void BfbIDMTCurveinit(BfbIDMTCurve* me);

/* Function block execution function */
void BfbIDMTCurverun(BfbIDMTCurve* me);

/* ECC algorithms */
void BfbIDMTCurve_ResetCnt(BfbIDMTCurve* me);
void BfbIDMTCurve_UpdateCnt(BfbIDMTCurve* me);
void BfbIDMTCurve_UpdateMax(BfbIDMTCurve* me);

#endif // BFBIDMTCURVE_H_
