-- This file has been automatically generated by go-iec61499-vhdl and should not be edited by hand
-- Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499-vhdl

-- This file represents the Composite Function Block for DE2_115

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;



entity DE2_115 is

	port(
		--for clock and reset signal
		clk		: in	std_logic;
		reset	: in	std_logic;
		enable	: in	std_logic;
		sync	: in	std_logic;
		
		
		
		
		
		--special emitted internal variables for child I/O
		rx_conveyor_moving : in std_logic; --type was BOOL 
		rx_conveyor_jammed : in std_logic; --type was BOOL 
		tx_conveyor_run : out std_logic; --type was BOOL 
		rx_global_run : in std_logic; --type was BOOL 
		rx_global_run_infinite : in std_logic; --type was BOOL 
		rx_global_fault : in std_logic; --type was BOOL 
		tx_box_dropper_run : out std_logic; --type was BOOL 
		
		--for done signal
		done : out std_logic
	);

end entity;


architecture rtl of DE2_115 is
	-- Signals needed for event connections 
	signal globals_global_run_changed_conn : std_logic;

	-- Signals needed for data connections 
	signal globals_global_run_conn : std_logic; --type was BOOL
	signal globals_global_run_infinite_conn : std_logic; --type was BOOL

	-- Signals needed for the done signals 
	signal conveyor_done : std_logic;
	signal globals_done : std_logic;
	signal boxdropper_done : std_logic;
begin
	--top level I/O to signals
	
	-- child I/O to signals
	
	conveyor : entity work.Conveyor_SIFB port map(
		clk => clk,
		reset => reset,
		enable => enable,
		sync => sync,

		--event outputs 
		
		--event inputs
		conveyor_run_changed_eI => globals_global_run_changed_conn, 
		
		--data outputs
		
		--data inputs
		conveyor_run_I => globals_global_run_conn,
		

		--specials
		rx_conveyor_moving => rx_conveyor_moving, --input
		rx_conveyor_jammed => rx_conveyor_jammed, --input
		tx_conveyor_run => tx_conveyor_run, --output
		
		done => conveyor_done
	);
	
	globals : entity work.Globals_SIFB port map(
		clk => clk,
		reset => reset,
		enable => enable,
		sync => sync,

		--event outputs 
		global_run_changed_eO => globals_global_run_changed_conn,
		
		--event inputs
		
		--data outputs
		global_run_O => globals_global_run_conn, 
		global_run_infinite_O => globals_global_run_infinite_conn, 
		
		--data inputs
		

		--specials
		rx_global_run => rx_global_run, --input
		rx_global_run_infinite => rx_global_run_infinite, --input
		rx_global_fault => rx_global_fault, --input
		
		done => globals_done
	);
	
	boxdropper : entity work.BoxDropper_SIFB port map(
		clk => clk,
		reset => reset,
		enable => enable,
		sync => sync,

		--event outputs 
		
		--event inputs
		box_dropper_run_changed_eI => globals_global_run_changed_conn, 
		
		--data outputs
		
		--data inputs
		box_dropper_run_I => globals_global_run_infinite_conn,
		

		--specials
		tx_box_dropper_run => tx_box_dropper_run, --output
		
		done => boxdropper_done
	);
	

	-- done signal
	done <= conveyor_done and globals_done and boxdropper_done;
	
end rtl;
