// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Basic Function Block for AB5Policy
#include "FB_AB5Policy.h"


/* AB5Policy_preinit() is required to be called to 
 * initialise an instance of AB5Policy. 
 * It sets all I/O values to zero.
 */
int AB5Policy_preinit(AB5Policy_t  *me) {
	

	//reset the input events
	me->inputEvents.event.A = 0;
	
	//reset the output events
	me->outputEvents.event.B = 0;
	
	//set any input vars with default values
	
	//set any output vars with default values
	
	//set any internal vars with default values
	
	
	
	
	

	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	me->_state = STATE_AB5Policy_unknown;
	me->_trigger = true;
	
	
	

	return 0;
}

/* AB5Policy_init() is required to be called to 
 * set up an instance of AB5Policy. 
 * It passes around configuration data.
 */
int AB5Policy_init(AB5Policy_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	
	

	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//no algorithms were present for this function block


/* AB5Policy_run() executes a single tick of an
 * instance of AB5Policy according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 * Also note that on the first run of this function, trigger will already be set
 * to true, meaning that on the very first run no next state logic will occur.
 */
void AB5Policy_run(AB5Policy_t  *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.B = 0;
	
	
	
	//input policies
	
	//{{[{A  [] {0 }}] [{B  [] {0 }}] [] []} AB5 {[{v dtimer    {0 }}] [{s0 {0 }} {s1 {0 }}] [{{{s0 s0 not (A) and not (B)   {0 }} [{v 0}]} {{and 5 2 -1} [{{not 0 1 1} [{A}]} {{not 0 1 1} [{B}]}]}} {{{s0 s1 A and not (B)   {0 }} [{v 0}]} {{and 5 2 -1} [{A} {{not 0 1 1} [{B}]}]}} {{{s0 violation not (A) and B   {0 }} []} {{and 5 2 -1} [{{not 0 1 1} [{A}]} {B}]}} {{{s0 violation A and B   {0 }} []} {{and 5 2 -1} [{A} {B}]}} {{{s1 s1 not (A) and not (B) and v < 5   {0 }} []} {{and 5 2 -1} [{{and 5 2 -1} [{{not 0 1 1} [{A}]} {{not 0 1 1} [{B}]}]} {{< 4 2 -1} [{v} {5}]}]}} {{{s1 s0 not (A) and B   {0 }} []} {{and 5 2 -1} [{{not 0 1 1} [{A}]} {B}]}} {{{s1 violation v >= 5   {0 }} []} {{>= 4 2 -1} [{v} {5}]}} {{{s1 violation A and B   {0 }} []} {{and 5 2 -1} [{A} {B}]}} {{{s1 violation A and not (B)   {0 }} []} {{and 5 2 -1} [{A} {{not 0 1 1} [{B}]}]}}]} {[{v dtimer    {0 }}] [{s0 {0 }} {s1 {0 }}] [{{{s0 s0 not (A)   {0 }} [{v 0}]} {{not 0 1 1} [{A}]}} {{{s0 s1 A   {0 }} [{v 0}]} {A}} {{{s0 violation not (A)   {0 }} []} {{not 0 1 1} [{A}]}} {{{s0 violation A   {0 }} []} {A}} {{{s1 s1 5 < v and not (A)   {0 }} []} {{and 5 2 -1} [{{< 4 2 -1} [{5} {v}]} {{not 0 1 1} [{A}]}]}} {{{s1 s0 not (A)   {0 }} []} {{not 0 1 1} [{A}]}} {{{s1 violation 5 >= v   {0 }} []} {{>= 4 2 -1} [{5} {v}]}} {{{s1 violation A   {0 }} []} {A}}]}}
	
	


	
	//next state logic
	if(me->_trigger == false) {
		switch(me->_state) {
		
		}
	}

	//state output logic
	if(me->_trigger == true) {
		switch(me->_state) {
		
		}
	}

	me->_trigger = false;

	
//output policies


	//Ensure input events are cleared
	me->inputEvents.event.A = 0;
	
}


