// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block AB5Policy
#ifndef AB5POLICY_H_
#define AB5POLICY_H_

#include "fbtypes.h"
#include "util.h"



//This is a BFB with states, so we need an enum type for the state machine
enum AB5Policy_states { STATE_AB5Policy_unknown };


//This is an FB with policies, so we need an enum type for the state machine of each policy

enum AB5Policy_policy_AB5_states { POLICY_STATE_AB5Policy_AB5_s0, POLICY_STATE_AB5Policy_AB5_s1 };


union AB5PolicyInputEvents {
	struct {
		UDINT A;
	} event;
	
};


union AB5PolicyOutputEvents {
	struct {
		UDINT B;
	} event;
	
};


typedef struct {
    //input events
	union AB5PolicyInputEvents inputEvents;

    //output events
	union AB5PolicyOutputEvents outputEvents;

    //input vars
	
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum AB5Policy_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
	
	

	//this block has policies
	enum AB5Policy_policy_AB5_states _policy_AB5_state;
	//input vars
	//output vars
	DTIMER v;
	
	
	

} AB5Policy_t;

//all FBs get a preinit function
int AB5Policy_preinit(AB5Policy_t  *me);

//all FBs get an init function
int AB5Policy_init(AB5Policy_t  *me);

//all FBs get a run function
void AB5Policy_run(AB5Policy_t  *me);



#endif
