// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block Flipsign
#ifndef FLIPSIGN_H_
#define FLIPSIGN_H_

#include "fbtypes.h"
#include "util.h"



//This is a BFB with states, so we need an enum type for the state machine
enum Flipsign_states { STATE_Flipsign_reset, STATE_Flipsign_update };




union FlipsignInputEvents {
	struct {
		UDINT InChange;
	} event;
	
};


union FlipsignOutputEvents {
	struct {
		UDINT OutChange;
	} event;
	
};


typedef struct {
    //input events
	union FlipsignInputEvents inputEvents;

    //output events
	union FlipsignOutputEvents outputEvents;

    //input vars
	LREAL In;
    
    //output vars
	LREAL Out;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum Flipsign_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
	
	

	

} Flipsign_t;

//all FBs get a preinit function
int Flipsign_preinit(Flipsign_t  *me);

//all FBs get an init function
int Flipsign_init(Flipsign_t  *me);

//all FBs get a run function
void Flipsign_run(Flipsign_t  *me);



#endif
