// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block watertank
#ifndef WATERTANK_H_
#define WATERTANK_H_

#include "fbtypes.h"
#include "util.h"


#include "cvode/cvode.h"
#include "nvector/nvector_serial.h"
#include "cvode/cvode_dense.h"
#include "sundials/sundials_dense.h"
#include "sundials/sundials_types.h"


//This is a BFB, so we need an enum type for the state machine
enum watertank_states { STATE_watertank_Start, STATE_watertank_State1E0, STATE_watertank_State1, STATE_watertank_State2E0, STATE_watertank_State2, STATE_watertank_State3E0, STATE_watertank_State3, STATE_watertank_State4E0, STATE_watertank_State4, STATE_watertank_State2E1, STATE_watertank_State4E1, STATE_watertank_State1E1 };


union watertankInputEvents {
	struct {
		UDINT ON;
		UDINT OFF;
	} event;
	
};


union watertankOutputEvents {
	struct {
		UDINT update;
	} event;
	
};


typedef struct {
    //input events
	union watertankInputEvents inputEvents;

    //output events
	union watertankOutputEvents outputEvents;

    //input vars
	LREAL K;
    LREAL h;
    LREAL DeltaTime;
    
    //output vars
	LREAL x;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum watertank_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	//this block uses cvode
	void *cvode_mem;
	N_Vector ode_solution;
	realtype T0;
	realtype Tnext;
	realtype Tcurr;
	int solveInProgress;
	

	
} watertank_t;

//all FBs get a preinit function
int watertank_preinit(watertank_t  *me);

//all FBs get an init function
int watertank_init(watertank_t  *me);

//all FBs get a run function
void watertank_run(watertank_t  *me);



#endif
