// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block container_two_basic
#ifndef CONTAINER_TWO_BASIC_H_
#define CONTAINER_TWO_BASIC_H_

#include "fbtypes.h"

//This is a CFB, so we need the #includes for the child blocks embedded here
#include "passforward.h"
#include "passforward.h"


union container_two_basicInputEvents {
	struct {
		INT DataInChanged;
	} event;
};


union container_two_basicOutputEvents {
	struct {
		UDINT DataOutChanged : 1;
	} event;
	UDINT events[1];
};


typedef struct {
    //input events
	union container_two_basicInputEvents inputEvents;

    //output events
	union container_two_basicOutputEvents outputEvents;

    //input vars
	INT DataIn;
    INT printf_id1;
    INT printf_id2;
    
    //output vars
	INT DataOut;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	passforward_t pf1;
	passforward_t pf2;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
} container_two_basic_t;

//all FBs get a preinit function
int container_two_basic_preinit(container_two_basic_t  *me);

//all FBs get an init function
int container_two_basic_init(container_two_basic_t  *me);

//all FBs get a run function
void container_two_basic_run(container_two_basic_t  *me);

//composite/resource/device FBs get sync functions
void container_two_basic_syncOutputEvents(container_two_basic_t  *me);
void container_two_basic_syncInputEvents(container_two_basic_t  *me);

void container_two_basic_syncOutputData(container_two_basic_t  *me);
void container_two_basic_syncInputData(container_two_basic_t  *me);



#endif
