// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Basic Function Block for passforward
#include "FB_passforward.h"


/* passforward_preinit() is required to be called to 
 * initialise an instance of passforward. 
 * It sets all I/O values to zero.
 */
int passforward_preinit(passforward_t  *me) {
	//if there are input events, reset them
	me->inputEvents.event.DataInChanged = 0;
	
	//if there are output events, reset them
	me->outputEvents.event.DataOutChanged = 0;
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	me->_state = STATE_passforward_Start;
	me->_trigger = true;
	
	
	

	return 0;
}

/* passforward_init() is required to be called to 
 * set up an instance of passforward. 
 * It passes around configuration data.
 */
int passforward_init(passforward_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//algorithms

void passforward_upcount(passforward_t  *me) {
//PROVIDED CODE: this algorithm was provided in an algorithm's text field
printf("PF[%2i]: Received %i\n", me->printf_id, me->DataIn);
me->DataOut = me->DataIn + 1;
}



/* passforward_run() executes a single tick of an
 * instance of passforward according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 * Also note that on the first run of this function, trigger will be set
 * to true, meaning that on the very first run no next state logic will occur.
 */
void passforward_run(passforward_t  *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.DataOutChanged = 0;
	

	//next state logic
	if(me->_trigger == false) {
		switch(me->_state) {
		case STATE_passforward_Start:
			if(true) {
				me->_state = STATE_passforward_emit_data;
				me->_trigger = true;
			};
			break;
		case STATE_passforward_emit_data:
			if(me->inputEvents.event.DataInChanged) {
				me->_state = STATE_passforward_count;
				me->_trigger = true;
			};
			break;
		case STATE_passforward_count:
			if(true) {
				me->_state = STATE_passforward_emit_data;
				me->_trigger = true;
			};
			break;
		
		}
	}

	//state output logic
	if(me->_trigger == true) {
		switch(me->_state) {
		case STATE_passforward_Start:
			break;

		case STATE_passforward_emit_data:
			me->outputEvents.event.DataOutChanged = 1;
			break;

		case STATE_passforward_count:
			passforward_upcount(me);
			break;

		
		}
	}

	me->_trigger = false;
}


