// This file has been automatically generated by goFB
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

//This is the main file for the iec61499 network with topFLAT as the top level block

#include "FB_topFLAT.h"
#include <sys/time.h>

#ifndef MAX_TICKS
#define MAX_TICKS 100
#endif

//put a copy of the top level block into global memory
topFLAT_t mytopFLAT;

int main() {
	//printf("\n\n\n");
	//printf("\nTop: %20s   Size: %lu\n", "topFLAT", sizeof(mytopFLAT));

	#ifdef PRINT_VALS
	printf("Simulation time,");
	#endif

	if(topFLAT_preinit(&mytopFLAT) != 0) {
		printf("Failed to preinitialize.");
		return 1;
	}
	if(topFLAT_init(&mytopFLAT) != 0) {
		printf("Failed to initialize.");
		return 1;
	}
	printf("\n");
	
	struct timeval tv1, tv2;
	gettimeofday(&tv1, NULL);

	int tickNum = 1;
	do {
		#ifdef PRINT_VALS
			printf("%f,",(double)tickNum*0.01);
		#endif
		topFLAT_syncOutputEvents(&mytopFLAT);
		topFLAT_syncInputEvents(&mytopFLAT);

		topFLAT_syncOutputData(&mytopFLAT);
		topFLAT_syncInputData(&mytopFLAT);
		
		topFLAT_run(&mytopFLAT);
		#ifdef PRINT_VALS
			printf("\n");
		#endif
	} while(tickNum++ < MAX_TICKS);
	gettimeofday(&tv2, NULL);
	#ifdef PRINT_TIME
	printf ("Total time = %f seconds\n",
         (double) (tv2.tv_usec - tv1.tv_usec) / 1000000 +
         (double) (tv2.tv_sec - tv1.tv_sec));
	#endif
	return 0;
}

