// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block CfbBreakerController
#ifndef CFBBREAKERCONTROLLER_H_
#define CFBBREAKERCONTROLLER_H_

#include "fbtypes.h"
#include "util.h"



//This is a CFB, so we need the #includes for the child blocks embedded here
#include "FB_BfbSetterResetter.h"
#include "FB_BfbIDMTCurve.h"




union CfbBreakerControllerInputEvents {
	struct {
		UDINT tick;
		UDINT i_measured;
		UDINT test;
		UDINT set;
		UDINT iSet_change;
	} event;
	
};


union CfbBreakerControllerOutputEvents {
	struct {
		UDINT b_change;
	} event;
	
};


typedef struct {
    //input events
	union CfbBreakerControllerInputEvents inputEvents;

    //output events
	union CfbBreakerControllerOutputEvents outputEvents;

    //input vars
	USINT i;
    USINT iSet;
    
    //output vars
	BOOL b;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	BfbSetterResetter_t sr;
	BfbIDMTCurve_t curve;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
	

	

} CfbBreakerController_t;

//all FBs get a preinit function
int CfbBreakerController_preinit(CfbBreakerController_t  *me);

//all FBs get an init function
int CfbBreakerController_init(CfbBreakerController_t  *me);

//all FBs get a run function
void CfbBreakerController_run(CfbBreakerController_t  *me);

//composite/resource/device FBs get sync functions
void CfbBreakerController_syncOutputEvents(CfbBreakerController_t  *me);
void CfbBreakerController_syncInputEvents(CfbBreakerController_t  *me);

void CfbBreakerController_syncOutputData(CfbBreakerController_t  *me);
void CfbBreakerController_syncInputData(CfbBreakerController_t  *me);



#endif
