// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Basic Function Block for SifbTimer
#include "FB_SifbTimer.h"


/* SifbTimer_preinit() is required to be called to 
 * initialise an instance of SifbTimer. 
 * It sets all I/O values to zero.
 */
int SifbTimer_preinit(SifbTimer_t  *me) {
	

	
	//reset the output events
	me->outputEvents.event.Tick = 0;
	
	//set any input vars with default values
	
	//set any output vars with default values
	
	//set any internal vars with default values
	
	
	
	
	

	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	//me->_state = STATE_SifbTimer_Start;
	//me->_trigger = true;
	
	
	

	

	return 0;
}

/* SifbTimer_init() is required to be called to 
 * set up an instance of SifbTimer. 
 * It passes around configuration data.
 */
int SifbTimer_init(SifbTimer_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	
	
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//no algorithms were present for this function block


/* SifbTimer_run() executes a single tick of an
 * instance of SifbTimer according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 * Also note that on the first run of this function, trigger will already be set
 * to true, meaning that on the very first run no next state logic will occur.
 */
void SifbTimer_run(SifbTimer_t  *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.Tick = 0;
	
	
	

	
	// //next state logic
	// if(me->_trigger == false) {
	// 	switch(me->_state) {
	// 	case STATE_SifbTimer_Start:
	// 		if(true) {
				
	// 			me->_state = STATE_SifbTimer_Start;
	// 			me->_trigger = true;
	// 		};
	// 		break;
		
	// 	default: 
	// 		break;
	// 	}
	// }

	//state output logic
	// if(me->_trigger == true) {
	// 	switch(me->_state) {
	// 	case STATE_SifbTimer_Start:
	// 		#ifdef PRINT_STATES
	// 			printf("SifbTimer: [Entered State Start]\n");
	// 		#endif
			me->outputEvents.event.Tick = 1;
			
	// 		break;
		
	// 	default: 
	// 		break;
	// 	}
	// }

	// me->_trigger = false;

	

	//Ensure input events are cleared
	
}


