// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Basic Function Block for BfbSetterResetter
#include "FB_BfbSetterResetter.h"


/* BfbSetterResetter_preinit() is required to be called to 
 _SPM * initialise an instance of BfbSetterResetter. 
 _SPM * It sets all I/O values to zero.
 _SPM */
int BfbSetterResetter_preinit(BfbSetterResetter_t  _SPM *me) {
	

	//reset the input events
	me->inputEvents.event.brk = 0;
	//reset the input events
	me->inputEvents.event.rst = 0;
	//reset the input events
	me->inputEvents.event.unsafe = 0;
	
	//reset the output events
	me->outputEvents.event.b_change = 0;
	
	//set any input vars with default values
	
	//set any output vars with default values
	
	//set any internal vars with default values
	
	
	
	
	

	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	me->_state = STATE_BfbSetterResetter_INIT;
	me->_trigger = true;
	
	
	

	

	return 0;
}

/* BfbSetterResetter_init() is required to be called to 
 _SPM * set up an instance of BfbSetterResetter. 
 _SPM * It passes around configuration data.
 _SPM */
int BfbSetterResetter_init(BfbSetterResetter_t  _SPM *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	
	
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//algorithms

void BfbSetterResetter_BreakB(BfbSetterResetter_t  _SPM *me) {
//PROVIDED CODE: this algorithm was provided in an algorithm's text field
me->b = 1;
}

void BfbSetterResetter_CloseB(BfbSetterResetter_t  _SPM *me) {
//PROVIDED CODE: this algorithm was provided in an algorithm's text field
me->b = 0;
}



/* BfbSetterResetter_run() executes a single tick of an
 _SPM * instance of BfbSetterResetter according to synchronous semantics.
 _SPM * Notice that it does NOT perform any I/O - synchronisation
 _SPM * will need to be done in the parent.
 _SPM * Also note that on the first run of this function, trigger will already be set
 _SPM * to true, meaning that on the very first run no next state logic will occur.
 _SPM */
void BfbSetterResetter_run(BfbSetterResetter_t  _SPM *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.b_change = 0;
	
	
	

	
	//next state logic
	if(me->_trigger == false) {
		switch(me->_state) {
		case STATE_BfbSetterResetter_INIT:
			if(true) {
				
				me->_state = STATE_BfbSetterResetter_OPEN_CONTACTS;
				me->_trigger = true;
			};
			break;
		case STATE_BfbSetterResetter_OPEN_CONTACTS:
			if(me->inputEvents.event.rst) {
				
				me->_state = STATE_BfbSetterResetter_CLOSE_CONTACTS;
				me->_trigger = true;
			};
			break;
		case STATE_BfbSetterResetter_CLOSE_CONTACTS:
			if(me->inputEvents.event.brk || me->inputEvents.event.unsafe) {
				
				me->_state = STATE_BfbSetterResetter_OPEN_CONTACTS;
				me->_trigger = true;
			};
			break;
		
		default: 
			break;
		}
	}

	//state output logic
	if(me->_trigger == true) {
		switch(me->_state) {
		case STATE_BfbSetterResetter_INIT:
			#ifdef PRINT_STATES
				printf("BfbSetterResetter: [Entered State INIT]\n");
			#endif
			
			break;
		case STATE_BfbSetterResetter_OPEN_CONTACTS:
			#ifdef PRINT_STATES
				printf("BfbSetterResetter: [Entered State OPEN_CONTACTS]\n");
			#endif
			BfbSetterResetter_BreakB(me);
			me->outputEvents.event.b_change = 1;
			
			break;
		case STATE_BfbSetterResetter_CLOSE_CONTACTS:
			#ifdef PRINT_STATES
				printf("BfbSetterResetter: [Entered State CLOSE_CONTACTS]\n");
			#endif
			BfbSetterResetter_CloseB(me);
			me->outputEvents.event.b_change = 1;
			
			break;
		
		default: 
			break;
		}
	}

	me->_trigger = false;

	

	//Ensure input events are cleared
	me->inputEvents.event.brk = 0;
	me->inputEvents.event.rst = 0;
	me->inputEvents.event.unsafe = 0;
	
}


