// This file has been automatically generated by goFB
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

//This is the main file for the iec61499 network with TrainGate as the top level block

#include "FB_TrainGate.h"

//put a copy of the top level block into global memory
TrainGate_t myTrainGate;

int main() {
	printf("\n\n\n");

	if(TrainGate_preinit(&myTrainGate) != 0) {
		printf("Failed to preinitialize.");
		return 1;
	}
	if(TrainGate_init(&myTrainGate) != 0) {
		printf("Failed to initialize.");
		return 1;
	}

	printf("Top: %20s   Size: %lu\n", "TrainGate", sizeof(myTrainGate));

	int tickNum = 0;
	do {
		printf("\nTick %i\n",tickNum);
		TrainGate_syncOutputEvents(&myTrainGate);
		TrainGate_syncInputEvents(&myTrainGate);

		TrainGate_syncOutputData(&myTrainGate);
		TrainGate_syncInputData(&myTrainGate);
		
		TrainGate_run(&myTrainGate);
		printf("\n");
	} while(tickNum++ < 200);

	return 0;
}

