// This file is generated by FBC.

// 

#include "Resource__CBCore0.h"
#include "Resource1__CBCore1.h"
#include "Resource2__CBCore2.h"
#include "Resource3__CBCore3.h"

int main(void)
{
    
    Resource__CBCore0 Resource;
    Resource__CBCore0init(&Resource);
    Resource1__CBCore1 Resource1;
    Resource1__CBCore1init(&Resource1);
    Resource2__CBCore2 Resource2;
    Resource2__CBCore2init(&Resource2);
    Resource3__CBCore3 Resource3;
    Resource3__CBCore3init(&Resource3);
    
    for (;;) {
        Resource__CBCore0run(&Resource);
        Resource1__CBCore1run(&Resource1);
        Resource2__CBCore2run(&Resource2);
        Resource3__CBCore3run(&Resource3);
    }

    return 0;
}
