// This file is generated by FBC.

#include "ArgoRx.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void ArgoRxinit(ArgoRx* me)
{
    me->_entered = false;
    me->_output.events = 0;
}

/* Function block execution function */
void ArgoRxrun(ArgoRx* me)
{
    me->_output.events = 0;

    // State: Start
    if (!me->_entered) {
        me->_entered = true;
    }
    if (me->_output.event.DataPresent) {
        me->_Data = me->Data;
    }

}

