// This file is generated by FBC.

#ifndef CFBBREAKERCONTROLLER_H_
#define CFBBREAKERCONTROLLER_H_

#include "fbtypes.h"
#include "BfbIDMTCurve.h"
#include "BfbSetterResetter.h"

typedef union {
    UDINT events;
    struct {
        UDINT tick : 1; // 
        UDINT i_measured : 1; // 
        UDINT i_set_change : 1; // 
        UDINT brk : 1; // 
        UDINT rst : 1; // 
    } event;
} CfbBreakerControllerIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT b_change : 1; // 
    } event;
} CfbBreakerControllerOEvents;

typedef struct {
    CfbBreakerControllerIEvents _input;
    REAL _i;
    REAL _i_set;
    CfbBreakerControllerOEvents _output;
    INT _b;
    BfbIDMTCurve idmtcurve;
    BfbSetterResetter setterresetter;
} CfbBreakerController;

/* Function block initialization function */
void CfbBreakerControllerinit(CfbBreakerController* me);

/* Function block execution function */
void CfbBreakerControllerrun(CfbBreakerController* me);

#endif // CFBBREAKERCONTROLLER_H_
