// This file is generated by FBC.

#ifndef SIFBINTLED_H_
#define SIFBINTLED_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT i_change : 1; // 
    } event;
} SifbIntLedIEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    SifbIntLedIEvents _input;
    INT i; // 
    INT _i;
} SifbIntLed;

/* Function block initialization function */
void SifbIntLedinit(SifbIntLed* me);

/* Function block execution function */
void SifbIntLedrun(SifbIntLed* me);

/* ECC algorithms */
void SifbIntLed_update_led(SifbIntLed* me);

#endif // SIFBINTLED_H_
