{{define "basicFB"}}// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499
{{$block := index .Blocks .BlockIndex}}{{$blocks := .Blocks}}{{$basicFB := $block.BasicFB}}
// This file represents the implementation of the Basic Function Block for {{$block.Name}}
#include "{{$block.Name}}.h"

void {{$block.Name}}_init(struct {{$block.Name}} *me) {
	//if there are output events, reset them
	{{if $block.EventOutputs}}{{range $index, $event := $block.EventOutputs.Events}}{{$event.Name}}[0] = 0;
	{{$event.Name}}[1] = 0;
	{{end}}{{end}}
	//if there are output vars, reset them
	{{if $block.OutputVars}}{{range $index, $var := $block.OutputVars.Variables}}{{$var.Name}} = 0;
	{{end}}{{end}}
	//if there are internal vars, reset them
	{{if $block.BasicFB.InternalVars}}{{range $varIndex, $var := $block.BasicFB.InternalVars.Variables}}{{$var.Name}} = 0;
	{{end}}{{end}}
}

void {{$block.Name}}_run(struct {{$block.Name}} *me) {

}

{{end}}