// This file is generated by FBC.

#ifndef HIGHESTREQUESTPRODUCER_H_
#define HIGHESTREQUESTPRODUCER_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT MotorDirectionUp : 1; // 
        UDINT MotorDirectionDown : 1; // 
        UDINT MotorDirectionIdle : 1; // 
        UDINT FloorSensor : 1; // 
        UDINT PendingReq : 1; // 
    } event;
} HighestRequestProducerIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CurrentPriority : 1; // 
    } event;
} HighestRequestProducerOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    HighestRequestProducerIEvents _input;
    INT FloorSensorValue; // 
    INT _FloorSensorValue;
    BOOL PendingReqValue[4]; // 
    BOOL _PendingReqValue[4];
    HighestRequestProducerOEvents _output;
    INT CurrentPriorityValue; // 
    INT _CurrentPriorityValue;
} HighestRequestProducer;

/* Function block initialization function */
void HighestRequestProducerinit(HighestRequestProducer* me);

/* Function block execution function */
void HighestRequestProducerrun(HighestRequestProducer* me);

/* ECC algorithms */
void HighestRequestProducer_ResolvePriorityUp(HighestRequestProducer* me);
void HighestRequestProducer_ResolvePriorityDown(HighestRequestProducer* me);
void HighestRequestProducer_ResolvePriorityIdle(HighestRequestProducer* me);

#endif // HIGHESTREQUESTPRODUCER_H_
