// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB
// Verilog support is EXPERIMENTAL ONLY

// This file represents the Composite Function Block for CfbTlNetwork

module FB_CfbTlNetwork 

(
		input wire clk,
		
		
		
		
		

		input reset
);


//Wires needed for event connections 


//Wires needed for data connections 


//top level I/O to signals


// child I/O to signals



endmodule