// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block BfbSetterResetter
#ifndef BFBSETTERRESETTER_H_
#define BFBSETTERRESETTER_H_

#include "fbtypes.h"
#include "util.h"



//This is a BFB with states, so we need an enum type for the state machine
enum BfbSetterResetter_states { STATE_BfbSetterResetter_INIT, STATE_BfbSetterResetter_OPEN_CONTACTS, STATE_BfbSetterResetter_CLOSE_CONTACTS };




union BfbSetterResetterInputEvents {
	struct {
		UDINT brk;
		UDINT rst;
		UDINT unsafe;
	} event;
	
};


union BfbSetterResetterOutputEvents {
	struct {
		UDINT b_change;
	} event;
	
};


typedef struct {
    //input events
	union BfbSetterResetterInputEvents inputEvents;

    //output events
	union BfbSetterResetterOutputEvents outputEvents;

    //input vars
	
    //output vars
	INT b;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum BfbSetterResetter_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
	
	

	

} BfbSetterResetter_t;

//all FBs get a preinit function
int BfbSetterResetter_preinit(BfbSetterResetter_t  _SPM *me);

//all FBs get an init function
int BfbSetterResetter_init(BfbSetterResetter_t  _SPM *me);

//all FBs get a run function
void BfbSetterResetter_run(BfbSetterResetter_t  _SPM *me);



#endif
