// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Composite Function Block for plant
#include "FB_plant.h"

//When running a composite block, note that you would call the functions in this order (and this is very important)
//_preinit(); 
//_init();
//do {
//	_syncOutputEvents();
//	_syncInputEvents();
//	_syncOutputData();
//	_syncInputData();
//	_run();
//} loop;


/* plant_preinit() is required to be called to 
 * initialise an instance of plant. 
 * It sets all I/O values to zero.
 */
int plant_preinit(plant_t  *me) {
	//if there are input events, reset them
	me->inputEvents.event.TURNON = 0;
	me->inputEvents.event.TURNOFF = 0;
	
	//if there are output events, reset them
	me->outputEvents.event.update = 0;
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(burner_preinit(&me->b) != 0) {
		return 1;
	}
	if(watertank_preinit(&me->w) != 0) {
		return 1;
	}
	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	

	return 0;
}

/* plant_init() is required to be called to 
 * set up an instance of plant. 
 * It passes around configuration data.
 */
int plant_init(plant_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	me->y = me->b.y;
	me->x = me->w.x;
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(burner_init(&me->b) != 0) {
		return 1;
	}
	if(watertank_init(&me->w) != 0) {
		return 1;
	}
	
	

	return 0;
}



/* plant_syncOutputEvents() synchronises the output events of an
 * instance of plant as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void plant_syncOutputEvents(plant_t  *me) {
	//first, for all cfb children, call this same function
	
	
	//then, for all connections that are connected to an output on the parent, run their run their copy
	
	me->outputEvents.event.update = me->b.outputEvents.event.update || me->w.outputEvents.event.update; 
	
}

/* plant_syncInputEvents() synchronises the input events of an
 * instance of plant as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void plant_syncInputEvents(plant_t  *me) {
	//first, we explicitly synchronise the children
	
	me->b.inputEvents.event.TURNON = me->inputEvents.event.TURNON; 
	
	me->b.inputEvents.event.TURNOFF = me->inputEvents.event.TURNOFF; 
	
	me->w.inputEvents.event.ON = me->b.outputEvents.event.ON; 
	
	me->w.inputEvents.event.OFF = me->b.outputEvents.event.OFF; 
	

	//then, call this same function on all cfb children
	
}

/* plant_syncOutputData() synchronises the output data connections of an
 * instance of plant as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void plant_syncOutputData(plant_t  *me) {
	//for all composite function block children, call this same function
	
	
	//for data that is sent from child to this CFB (me), always copy (event controlled copies will be resolved at the next level up) //TODO: arrays!?
	me->y = me->b.y;
	me->x = me->w.x;
	
	
}

/* plant_syncInputData() synchronises the input data connections of an
 * instance of plant as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void plant_syncInputData(plant_t  *me) {
	//for all basic function block children, perform their synchronisations explicitly
	
	//sync for b (of type burner) which is a BFB
	
	
	//sync for w (of type watertank) which is a BFB
	
	
	
	//for all composite function block children, call this same function
	
	
}


/* plant_run() executes a single tick of an
 * instance of plant according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void plant_run(plant_t  *me) {
	burner_run(&me->b);
	watertank_run(&me->w);
	
}

