// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block CanisterCounter
#include "fbtypes.h"



union CanisterCounterInputEvents {
	struct {
		UDINT LasersChanged : 1;
	} event;
	UDINT events[1];
};

union CanisterCounterOutputEvents {
	struct {
		UDINT CanisterCountChanged : 1;
	} event;
	UDINT events[1];
};

struct CanisterCounter {
    //input events
    union CanisterCounterInputEvents inputEvents;

    //output events
    union CanisterCounterOutputEvents outputEvents;

    //input vars
	BOOL DoorSiteLaser;
    BOOL RejectBinLaser;
    BOOL AcceptBinLaser;
    
    //output vars
	BYTE CanisterCount;
    
    //internal vars
	//child FBs 
	
};

//all FBs get an init function
void CanisterCounter_init(struct CanisterCounter *me);

//all FBs get a run function
void CanisterCounter_run(struct CanisterCounter *me);


//basic FBs have a number of algorithm functions

void CanisterCounter_ChangeCount(struct CanisterCounter *me);


