// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the implementation of the Basic Function Block for ConveyorController
#include "ConveyorController.h"

void ConveyorController_init(struct ConveyorController *me) {
	//if there are output events, reset them
	ConveyorChanged[0] = 0;
	ConveyorChanged[1] = 0;
	ConveyorStoppedForInject[0] = 0;
	ConveyorStoppedForInject[1] = 0;
	
	//if there are output vars, reset them
	ConveyorSpeed = 0;
	
	//if there are internal vars, reset them
	Variable1 = 0;
	
}

void ConveyorController_run(struct ConveyorController *me) {

}

