// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the implementation of the Basic Function Block for DoorController
#include "DoorController.h"

enum DoorController_states { STATE_E_Stop, STATE_Run, STATE_Await };

/* DoorController_init() is required to be called to 
 * initialise an instance of DoorController. 
 * It sets all I/O values to zero.
 */
void DoorController_init(struct DoorController *me) {
	//if there are input events, reset them
	me->inputEvents.events[0] = 0;
	
	//if there are output events, reset them
	me->outputEvents.events[0] = 0;
	
	//if there are input vars, reset them
	me->EmergencyStop = 0;
	
	//if there are output vars, reset them
	
	//if there are internal vars, reset them
	
}

/* DoorController_run() executes a single tick of an
 * instance of DoorController according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 */
void DoorController_run(struct DoorController *me) {
	//current state storage
	static enum DoorController_states state = STATE_E_Stop;
	static BOOL trigger = true; //should be true the first time this is run

	//if there are output events, reset them
	me->outputEvents.events[0] = 0;
	
	//now, let's advance state
	switch(state) {
	case STATE_E_Stop:
		if(me->inputEvents.event.EmergencyStopChanged && (!me->EmergencyStop)) {
			state = STATE_Await;
			trigger = true;
		};
		break;

	case STATE_Run:
		if(me->inputEvents.event.EmergencyStopChanged && (me->EmergencyStop)) {
			state = STATE_E_Stop;
			trigger = true;
		} else if(me->inputEvents.event.ReleaseDoorOverride || me->inputEvents.event.BottlingDone) {
			state = STATE_Run;
			trigger = true;
		};
		break;

	case STATE_Await:
		if(me->inputEvents.event.ReleaseDoorOverride || me->inputEvents.event.BottlingDone) {
			state = STATE_Run;
			trigger = true;
		};
		break;

	
	}

	//now, let's run any algorithms and emit any events that need to occur due to the trigger
	if(trigger == true) {
		switch(state) {
		case STATE_E_Stop:
			break;

		case STATE_Run:
			me->outputEvents.event.DoorReleaseCanister = 1;
			break;

		case STATE_Await:
			break;

		
		}
	}

	trigger = false;
}

//no algorithms were present for this function block


