// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block DoorController
#include "fbtypes.h"

union DoorControllerInputEvents {
	struct {
		UDINT ReleaseDoorOverride : 1;
		UDINT BottlingDone : 1;
		UDINT EmergencyStopChanged : 1;
	} event;
	UDINT events[1];
};

union DoorControllerOutputEvents {
	struct {
		UDINT DoorReleaseCanister : 1;
	} event;
	UDINT events[1];
};

struct DoorController {
    //input events
    union DoorControllerInputEvents inputEvents;

    //output events
    union DoorControllerOutputEvents outputEvents;

    //input vars
	BOOL EmergencyStop;
    
    //output vars
	
    //internal vars
	
};

void DoorController_init(struct DoorController *me);

void DoorController_run(struct DoorController *me);




