// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block DoorController
#include "fbtypes.h"

struct DoorControllerInputEvents {
	EVENT ReleaseDoorOverride;
	EVENT BottlingDone;
	EVENT EmergencyStopChanged;
}

struct DoorControllerOutputEvents {
	EVENT DoorReleaseCanister;
}







struct DoorController {
    //input events
    struct DoorControllerInputEvents inputEvents;

    //output events
    struct DoorControllerOutputEvents outputEvents;

    //input vars
    
    BOOL EmergencyStop;

    //output vars
    

    //internal vars
    

    
}

void DoorController_init(struct DoorController *me);

void DoorController_run(struct DoorController *me, int ev_offset);

