// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block flatFlexPRET
#ifndef FLATFLEXPRET_H_
#define FLATFLEXPRET_H_

#include "fbtypes.h"
#include "util.h"



//This is a CFB, so we need the #includes for the child blocks embedded here
#include "FB_IOManager.h"
#include "FB_CanisterCounter.h"
#include "FB_DoorController.h"
#include "FB_ConveyorController.h"
#include "FB_RejectArmController.h"
#include "FB_InjectorPumpsController.h"
#include "FB_InjectorMotorController.h"


//this block had no input events


//this block had no output events


typedef struct {
    //input events
	

    //output events
	

    //input vars
	
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	IOManager_t IO;
	CanisterCounter_t CCounter;
	DoorController_t Door;
	ConveyorController_t Conveyor;
	RejectArmController_t RejectArm;
	InjectorPumpsController_t Pumps;
	InjectorMotorController_t Motor;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
} flatFlexPRET_t;

//all FBs get a preinit function
int flatFlexPRET_preinit(flatFlexPRET_t  *me);

//all FBs get an init function
int flatFlexPRET_init(flatFlexPRET_t  *me);

//all FBs get a run function
void flatFlexPRET_run(flatFlexPRET_t  *me);

//composite/resource/device FBs get sync functions
void flatFlexPRET_syncOutputEvents(flatFlexPRET_t  *me);
void flatFlexPRET_syncInputEvents(flatFlexPRET_t  *me);

void flatFlexPRET_syncOutputData(flatFlexPRET_t  *me);
void flatFlexPRET_syncInputData(flatFlexPRET_t  *me);



#endif
