// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the implementation of the Composite Function Block for InjectorController
#include "InjectorController.h"

/* InjectorController_init() is required to be called to 
 * initialise an instance of InjectorController. 
 * As this is a composite function block, it contains no values of its own,
 * and so merely calls the initialisation routines of its children.
 */
void InjectorController_init(struct InjectorController *me) {
	InjectorMotorController_init(&me->Arm);
	InjectorPumpsController_init(&me->Pumps);
	
}

/* InjectorController_sync() synchronises an
 * instance of InjectorController according to synchronise semantics.
 * Notice that it does NOT perform any computation - additional steps
 * will need to be done at the parent.
 */
void InjectorController_sync(struct InjectorController *me) {
	//for all composite function block children, call this same function
	//for all basic function block children, perform their synchronisations explicitly
	
	//sync for Arm (of type InjectorMotorController) which is a BFB
	me->Arm.InputEvents.event.InjectorArmFinishedMovement = ?;
	me->Arm.InputEvents.event.EmergencyStopChanged = ?;
	me->Arm.InputEvents.event.ConveyorStoppedForInject = ?;
	me->Arm.InputEvents.event.PumpFinished = ?;
	
	//sync for Pumps (of type InjectorPumpsController) which is a BFB
	me->Pumps.InputEvents.event.StartPump = ?;
	me->Pumps.InputEvents.event.EmergencyStopChanged = ?;
	me->Pumps.InputEvents.event.CanisterPressureChanged = ?;
	me->Pumps.InputEvents.event.FillContentsAvailableChanged = ?;
	me->Pumps.InputEvents.event.VacuumTimerElapsed = ?;
	
}


/* InjectorController_run() executes a single tick of an
 * instance of InjectorController according to synchronise semantics.
 * Notice that it does NOT perform any I/O - additional synchronisation
 * will need to be done at the parent.
 */
void InjectorController_run(struct InjectorController *me) {
	InjectorMotorController_run(&me->Arm);
	InjectorPumpsController_run(&me->Pumps);
	
}

