// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block IOManager
#include "fbtypes.h"

union IOManagerInputEvents {
	struct {
		UDINT DoorReleaseCanister : 1;
		UDINT ConveyorChanged : 1;
		UDINT InjectorPositionChanged : 1;
		UDINT InjectorControlsChanged : 1;
		UDINT FillContentsChanged : 1;
		UDINT StartVacuumTimer : 1;
		UDINT GoRejectArm : 1;
		UDINT CanisterCountChanged : 1;
		UDINT InjectDone : 1;
	} event;
	UDINT events[1];
};

union IOManagerOutputEvents {
	struct {
		UDINT InjectorArmFinishMovement : 1;
		UDINT EmergencyStopChanged : 1;
		UDINT CanisterPressureChanged : 1;
		UDINT FillContentsAvailableChanged : 1;
		UDINT LasersChanged : 1;
		UDINT DoorOverride : 1;
		UDINT VacuumTimerElapsed : 1;
	} event;
	UDINT events[1];
};

struct IOManager {
    //input events
    union IOManagerInputEvents inputEvents;

    //output events
    union IOManagerOutputEvents outputEvents;

    //input vars
	BYTE ConveyorSpeed;
    BYTE InjectorPosition;
    BOOL InjectorContentsValveOpen;
    BOOL InjectorVacuumRun;
    BOOL InjectorPressurePumpRun;
    BOOL FillContents;
    BYTE CanisterCount;
    
    //output vars
	BOOL EmergencyStop;
    BYTE CanisterPressure;
    BYTE FillContentsAvailable;
    BOOL DoorSiteLaser;
    BOOL InjectSiteLaser;
    BOOL RejectSiteLaser;
    BOOL RejectBinLaser;
    BOOL AcceptBinLaser;
    
    //internal vars
	BOOL EmergencyStopped;
    
};

void IOManager_init(struct IOManager *me);

void IOManager_run(struct IOManager *me);


//algorithms

void IOManager_IOAlgorithm(struct IOManager *me);


