// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block IOManager
#include "fbtypes.h"

struct IOManagerInputEvents {
	EVENT *DoorReleaseCanister;
	EVENT *ConveyorChanged;
	EVENT *InjectorPositionChanged;
	EVENT *InjectorControlsChanged;
	EVENT *FillContentsChanged;
	EVENT *StartVacuumTimer;
	EVENT *GoRejectArm;
	EVENT *CanisterCountChanged;
	EVENT *InjectDone;
}

struct IOManagerOutputEvents {
	EVENT InjectorArmFinishMovement[2];
	EVENT EmergencyStopChanged[2];
	EVENT CanisterPressureChanged[2];
	EVENT FillContentsAvailableChanged[2];
	EVENT LasersChanged[2];
	EVENT DoorOverride[2];
	EVENT VacuumTimerElapsed[2];
}

struct IOManagerInputVars {
	BYTE ConveyorSpeed;
	BYTE InjectorPosition;
	BOOL InjectorContentsValveOpen;
	BOOL InjectorVacuumRun;
	BOOL InjectorPressurePumpRun;
	BOOL FillContents;
	BYTE CanisterCount;
}

struct IOManagerOutputVars {
	BOOL EmergencyStop;
	BYTE CanisterPressure;
	BYTE FillContentsAvailable;
	BOOL DoorSiteLaser;
	BOOL InjectSiteLaser;
	BOOL RejectSiteLaser;
	BOOL RejectBinLaser;
	BOOL AcceptBinLaser;
}

struct IOManagerInternalVars {
	BOOL EmergencyStopped;
	BYTE UART_TX;
	BOOL UART_TX_READY;
	BOOL UART_TX_SEND;
}

struct IOManager {
    struct IOManagerInputEvents inputEvents;
    struct IOManagerOutputEvents outputEvents;
    struct IOManagerInputVars inputVars;
    struct IOManagerOutputVars outputVars;
    struct IOManagerInternalVars internalVars;
}

void IOManager_init(struct IOManager *me);

void IOManager_run(struct IOManager *me);

