// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block RejectArmController
#include "fbtypes.h"

struct RejectArmControllerInputEvents {
	EVENT RejectCanister;
	EVENT LasersChanged;
}

struct RejectArmControllerOutputEvents {
	EVENT GoRejectArm;
}







struct RejectArmController {
    //input events
    struct RejectArmControllerInputEvents inputEvents;

    //output events
    struct RejectArmControllerOutputEvents outputEvents;

    //input vars
    
    BOOL RejectSiteLaser;

    //output vars
    

    //internal vars
    

    
}

void RejectArmController_init(struct RejectArmController *me);

void RejectArmController_run(struct RejectArmController *me, int ev_offset);

