// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block RejectArmController
#include "fbtypes.h"

union RejectArmControllerInputEvents {
	struct {
		UDINT RejectCanister : 1;
		UDINT LasersChanged : 1;
	} event;
	UDINT events[1];
};

union RejectArmControllerOutputEvents {
	struct {
		UDINT GoRejectArm : 1;
	} event;
	UDINT events[1];
};

struct RejectArmController {
    //input events
    union RejectArmControllerInputEvents inputEvents;

    //output events
    union RejectArmControllerOutputEvents outputEvents;

    //input vars
	BOOL RejectSiteLaser;
    
    //output vars
	
    //internal vars
	
};

void RejectArmController_init(struct RejectArmController *me);

void RejectArmController_run(struct RejectArmController *me);




