// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the interface of Function Block RejectArmController
#include "fbtypes.h"

struct RejectArmControllerInputEvents {
	EVENT *RejectCanister;
	EVENT *LasersChanged;
}

struct RejectArmControllerOutputEvents {
	EVENT GoRejectArm[2];
}

struct RejectArmControllerInputVars {
	BOOL RejectSiteLaser;
}

struct RejectArmControllerOutputVars {
}

struct RejectArmControllerInternalVars {
}

struct RejectArmController {
    struct RejectArmControllerInputEvents inputEvents;
    struct RejectArmControllerOutputEvents outputEvents;
    struct RejectArmControllerInputVars inputVars;
    struct RejectArmControllerOutputVars outputVars;
    struct RejectArmControllerInternalVars internalVars;
}

void RejectArmController_init(struct RejectArmController *me);

void RejectArmController_run(struct RejectArmController *me);

