// This file has been automatically generated by goFB
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

//This is the main file for the iec61499 network with FlexPRET as the top level block

#include "FB_FlexPRET.h"
#include <sys/time.h>

#ifndef MAX_TICKS
#define MAX_TICKS 100
#endif

//put a copy of the top level block into global memory
FlexPRET_t myFlexPRET;

int main() {
	//printf("\n\n\n");
	//printf("\nTop: %20s   Size: %lu\n", "FlexPRET", sizeof(myFlexPRET));

	#ifdef PRINT_VALS
	printf("Simulation time,");
	#endif

	if(FlexPRET_preinit(&myFlexPRET) != 0) {
		printf("Failed to preinitialize.");
		return 1;
	}
	if(FlexPRET_init(&myFlexPRET) != 0) {
		printf("Failed to initialize.");
		return 1;
	}
	printf("\n");
	
	struct timeval tv1, tv2;
	gettimeofday(&tv1, NULL);

	int tickNum = 1;
	do {
		#ifdef PRINT_VALS
			printf("%f,",(double)tickNum*0.01);
		#endif
		FlexPRET_syncOutputEvents(&myFlexPRET);
		FlexPRET_syncInputEvents(&myFlexPRET);

		FlexPRET_syncOutputData(&myFlexPRET);
		FlexPRET_syncInputData(&myFlexPRET);
		
		FlexPRET_run(&myFlexPRET);
		#ifdef PRINT_VALS
			printf("\n");
		#endif
	} while(tickNum++ < MAX_TICKS);
	gettimeofday(&tv2, NULL);
	#ifdef PRINT_TIME
	printf ("Total time = %f seconds\n",
         (double) (tv2.tv_usec - tv1.tv_usec) / 1000000 +
         (double) (tv2.tv_sec - tv1.tv_sec));
	#endif
	return 0;
}

