// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block LfcPrint
#ifndef LFCPRINT_H_
#define LFCPRINT_H_

#include "fbtypes.h"
#include "util.h"







union LfcPrintInputEvents {
	struct {
		UDINT Tick;
		UDINT DfDptDphChange;
		UDINT DprefChange;
	} event;
	
};


//this block had no output events


typedef struct {
    //input events
	union LfcPrintInputEvents inputEvents;

    //output events
	

    //input vars
	LREAL Df;
    LREAL Dpt;
    LREAL Dph;
    LREAL Dpref;
    
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	//Code provided in SIFB
	


	

	

} LfcPrint_t;

//all FBs get a preinit function
int LfcPrint_preinit(LfcPrint_t  *me);

//all FBs get an init function
int LfcPrint_init(LfcPrint_t  *me);

//all FBs get a run function
void LfcPrint_run(LfcPrint_t  *me);



#endif
