// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Composite Function Block for _Core002
#include "_Core002.h"

//When running a composite block, note that you would call the functions in this order (and this is very important)
//_preinit(); 
//_init();
//do {
//	_syncOutputEvents();
//	_syncInputEvents();
//	_syncOutputData();
//	_syncInputData();
//	_run();
//} loop;


/* _Core002_preinit() is required to be called to 
 * initialise an instance of _Core002. 
 * It sets all I/O values to zero.
 */
int _Core002_preinit(_Core002_t  *me) {
	//if there are input events, reset them
	
	//if there are output events, reset them
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(Print_preinit(&me->print) != 0) {
		return 1;
	}
	if(Gen_preinit(&me->gen) != 0) {
		return 1;
	}
	if(Pass_preinit(&me->Reference) != 0) {
		return 1;
	}
	
	
	//if this is a BFB, set _trigger to be true and start state so that the start state is properly executed
	

	return 0;
}

/* _Core002_init() is required to be called to 
 * set up an instance of _Core002. 
 * It passes around configuration data.
 */
int _Core002_init(_Core002_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	me->Reference.Count = me->gen.Count;
	me->print.Count = me->Reference.OutCount;
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(Print_init(&me->print) != 0) {
		return 1;
	}
	if(Gen_init(&me->gen) != 0) {
		return 1;
	}
	if(Pass_init(&me->Reference) != 0) {
		return 1;
	}
	
	

	return 0;
}



/* _Core002_syncOutputEvents() synchronises the output events of an
 * instance of _Core002 as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core002_syncOutputEvents(_Core002_t  *me) {
	//first, for all cfb children, call this same function
	
	
	//then, for all connections that are connected to an output on the parent, run their run their copy
	
}

/* _Core002_syncInputEvents() synchronises the input events of an
 * instance of _Core002 as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core002_syncInputEvents(_Core002_t  *me) {
	//first, we explicitly synchronise the children
	
	me->print.inputEvents.event.CountChanged = me->Reference.outputEvents.event.OutCountChanged; 
	
	me->Reference.inputEvents.event.CountChanged = me->gen.outputEvents.event.CountChanged; 
	

	//then, call this same function on all cfb children
	
}

/* _Core002_syncOutputData() synchronises the output data connections of an
 * instance of _Core002 as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core002_syncOutputData(_Core002_t  *me) {
	//for all composite function block children, call this same function
	
	
	//for data that is sent from child to this CFB (me), always copy (event controlled copies will be resolved at the next level up) //TODO: arrays!?
	
	
}

/* _Core002_syncInputData() synchronises the input data connections of an
 * instance of _Core002 as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core002_syncInputData(_Core002_t  *me) {
	//for all basic function block children, perform their synchronisations explicitly
	
	//sync for print (of type Print) which is a BFB
	
	if(me->print.inputEvents.event.CountChanged == 1) { 
		me->print.Count = me->Reference.OutCount;
	} 
	
	//sync for gen (of type Gen) which is a BFB
	
	
	//sync for Reference (of type Pass) which is a BFB
	
	if(me->Reference.inputEvents.event.CountChanged == 1) { 
		me->Reference.Count = me->gen.Count;
	} 
	
	
	//for all composite function block children, call this same function
	
	
}


/* _Core002_run() executes a single tick of an
 * instance of _Core002 according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void _Core002_run(_Core002_t  *me) {
	//Next block is BFB so we'll copy to SPM first
	Print_t _SPM *print_spm = SPM_BASE;
	spm_copy_from_ext(print_spm, &me->print, sizeof(Print_t));
	Print_run(print_spm);
	spm_copy_to_ext(&me->print, print_spm, sizeof(Print_t));
	
	//Next block is BFB so we'll copy to SPM first
	Gen_t _SPM *gen_spm = SPM_BASE;
	spm_copy_from_ext(gen_spm, &me->gen, sizeof(Gen_t));
	Gen_run(gen_spm);
	spm_copy_to_ext(&me->gen, gen_spm, sizeof(Gen_t));
	
	//Next block is BFB so we'll copy to SPM first
	Pass_t _SPM *Reference_spm = SPM_BASE;
	spm_copy_from_ext(Reference_spm, &me->Reference, sizeof(Pass_t));
	Pass_run(Reference_spm);
	spm_copy_to_ext(&me->Reference, Reference_spm, sizeof(Pass_t));
	
	
}

