// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB
// Verilog support is EXPERIMENTAL ONLY

// This file represents the Basic Function Block for BfbSetterResetter

module BfbSetterResetter 

(
		input wire clk,
		
		
		//input events
		input wire test_eI,
		input wire set_eI,
		input wire unsafe_eI,
		
		
		//output events
		output wire b_change_eO,
		
		
		
		//output variables
		output reg  b_O ,
		

		input reset
);


////BEGIN internal copies of I/O
//input events
wire test;
assign test = test_eI;
wire set;
assign set = set_eI;
wire unsafe;
assign unsafe = unsafe_eI;

//output events
reg b_change;
assign b_change_eO = b_change;


//output variables
reg  b;

////END internal copies of I/O

////BEGIN internal vars

////END internal vars

always@(posedge clk) begin
	//BEGIN update internal inputs

	//END update internal inputs



	//BEGIN update 

end
endmodule