// This file is generated by FBC.

#ifndef DOORCONTROLLER_H_
#define DOORCONTROLLER_H_

#include "fbtypes.h"

typedef union {
    struct {
        UDINT ReleaseDoorOverride ; // 
        UDINT BottlingDone ; // 
        UDINT EmergencyStopChanged ; // 
    } event;
} DoorControllerIEvents;

typedef union {
    struct {
        UDINT DoorReleaseCanister ; // 
    } event;
} DoorControllerOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    DoorControllerIEvents _input;
    BOOL EmergencyStop; // 
    BOOL _EmergencyStop;
    DoorControllerOEvents _output;
} DoorController;

/* Function block initialization function */
void DoorControllerinit(DoorController* me);

/* Function block execution function */
void DoorControllerrun(DoorController* me);

#endif // DOORCONTROLLER_H_
