// This file has been automatically generated by go-iec61499 and should not be edited by hand
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

// This file represents the implementation of the Basic Function Block for CounterBFB
#include "CounterBFB.h"

enum CounterBFB_states { STATE_Start };

/* CounterBFB_init() is required to be called to 
 * initialise an instance of CounterBFB. 
 * It sets all I/O values to zero.
 */
void CounterBFB_init(struct CounterBFB *me) {
	//if there are input events, reset them
	me->inputEvents.events[0] = 0;
	
	//if there are output events, reset them
	me->outputEvents.events[0] = 0;
	
	//if there are input vars, reset them
	
	//if there are output vars, reset them
	me->count = 10;
	
	//if there are internal vars, reset them
	
	//if there are any resource vars, reset them
	
}

/* CounterBFB_run() executes a single tick of an
 * instance of CounterBFB according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 */
void CounterBFB_run(struct CounterBFB *me) {
	//current state storage
	static enum CounterBFB_states state = STATE_Start;
	static BOOL trigger = true; //should be true the first time this is run

	//if there are output events, reset them
	me->outputEvents.events[0] = 0;
	
	//now, let's advance state
	switch(state) {
	case STATE_Start:
		if(me->inputEvents.event.in) {
			state = STATE_Start;
			trigger = true;
		};
		break;

	
	}

	//now, let's run any algorithms and emit any events that need to occur due to the trigger
	if(trigger == true) {
		switch(state) {
		case STATE_Start:
			CounterBFB_increaseCount(me);
			me->outputEvents.event.updated_count = 1;
			break;

		
		}
	}

	trigger = false;
}

//algorithms

void CounterBFB_increaseCount(struct CounterBFB *me) {
me->count++;
}



