// This file has been automatically generated by goFB
// Transpiler written by Hammond Pearce and available at github.com/kiwih/goFB

//This is the main file for the iec61499 network with test2 as the top level block

#include "test2.h"

//put a copy of the top level block into global memory
struct test2 mytest2;

int main() {
	if(test2_init(&mytest2) != 0) {
		printf("Failed to initialize.");
		return 1;
	}
	
	do {
		test2_syncEvents(&mytest2);
		test2_syncData(&mytest2);
		test2_run(&mytest2);
	} while(true);

	return 0;
}

