// This file has been automatically generated by go-iec61499 and should only be edited by hand
// to add support for I/O 
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

//This is the main file for the iec61499 network with ResourceType1 as the top level block

#include "ResourceType1.h"

//put a copy of the top level block into global memory
struct ResourceType1 myResourceType1;

void main() {
	ResourceType1_init(&myResourceType1);
	do {
		//resource I/O code can be put here
		me->Variable1 = 0;
		
		ResourceType1_syncEvents(&myResourceType1);
		ResourceType1_syncData(&myResourceType1);
		ResourceType1_run(&myResourceType1);
	} while(true);
}

