// This file has been automatically generated by go-iec61499 and should only be edited by hand
// to add support for I/O 
// Converter written by Hammond Pearce and available at github.com/kiwih/go-iec61499

//This is the main file for the iec61499 network with test2 as the top level block

#include "test2.h"

//put a copy of the top level block into global memory
struct test2 mytest2;

void main() {
	test2_init(&mytest2);
	do {
		test2_syncEvents(&mytest2);
		test2_syncData(&mytest2);
		test2_run(&mytest2);
	} while(true);
}

