// This file is generated by FBC.

#include "Pass.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void Passinit(Pass* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.event.CountChanged = 0;
    me->_output.event.OutCountChanged = 0;
}

/* ECC algorithms */
void Pass_UpdateCountOut(Pass* me)
{
me->OutCount = me->Count;
}

/* Function block execution function */
void Passrun(Pass* me)
{
    me->_output.event.OutCountChanged = 0;

    if (me->_input.event.CountChanged) {
        me->Count = me->_Count;
    }
	#pragma loopbound min 1 max 2
    for (;;) {
        if (me->_state == 0) {
            // State: Start
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                if (me->_input.event.CountChanged) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: update
            if (!me->_entered) {
                Pass_UpdateCountOut(me);
                me->_output.event.OutCountChanged = 1;
                me->_entered = true;
            }
            else {
                if (me->_input.event.CountChanged) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        break;
    }
    if (me->_output.event.OutCountChanged) {
        me->_OutCount = me->OutCount;
    }

    me->_input.event.CountChanged = 0;
}

