// This file is generated by FBC.

#include "Pass10.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void Pass10init(Pass10* me)
{
    me->_input.event.CountChanged = 0;
    me->_output.event.OutCountChanged = 0;
    Passinit(&me->p1);
    Passinit(&me->p2);
    Passinit(&me->p3);
    Passinit(&me->p4);
    Passinit(&me->p5);
    Passinit(&me->p9);
    Passinit(&me->p6);
    Passinit(&me->p10);
    Passinit(&me->p7);
    Passinit(&me->p8);
}

/* Function block execution function */
void Pass10run(Pass10* me)
{
    me->p1._Count = me->_Count;
    me->p1._input.event.CountChanged = me->_input.event.CountChanged;
    me->p2._Count = me->p1._OutCount;
    me->p2._input.event.CountChanged = me->p1._output.event.OutCountChanged;
    me->p3._input.event.CountChanged = me->p2._output.event.OutCountChanged;
    me->p3._Count = me->p2._OutCount;
    me->p4._input.event.CountChanged = me->p3._output.event.OutCountChanged;
    me->p4._Count = me->p3._OutCount;
    me->p5._Count = me->p4._OutCount;
    me->p5._input.event.CountChanged = me->p4._output.event.OutCountChanged;
    me->p9._input.event.CountChanged = me->p8._output.event.OutCountChanged;
    me->p9._Count = me->p8._OutCount;
    me->p6._Count = me->p5._OutCount;
    me->p6._input.event.CountChanged = me->p5._output.event.OutCountChanged;
    me->p10._input.event.CountChanged = me->p9._output.event.OutCountChanged;
    me->p10._Count = me->p9._OutCount;
    me->p7._Count = me->p6._OutCount;
    me->p7._input.event.CountChanged = me->p6._output.event.OutCountChanged;
    me->p8._Count = me->p7._OutCount;
    me->p8._input.event.CountChanged = me->p7._output.event.OutCountChanged;
    
    Passrun(&me->p1);
    Passrun(&me->p2);
    Passrun(&me->p3);
    Passrun(&me->p4);
    Passrun(&me->p5);
    Passrun(&me->p9);
    Passrun(&me->p6);
    Passrun(&me->p10);
    Passrun(&me->p7);
    Passrun(&me->p8);
    
    me->_OutCount = me->p10._OutCount;
    me->_output.event.OutCountChanged = me->p10._output.event.OutCountChanged;
}
