// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block ha_timer
#ifndef HA_TIMER_H_
#define HA_TIMER_H_

#include "fbtypes.h"
#include "util.h"


#include "cvode/cvode.h"
#include "nvector/nvector_serial.h"
#include "cvode/cvode_dense.h"
#include "sundials/sundials_dense.h"
#include "sundials/sundials_types.h"


//This is a BFB, so we need an enum type for the state machine
enum ha_timer_states { STATE_ha_timer_Start, STATE_ha_timer_State1E0, STATE_ha_timer_State1, STATE_ha_timer_State1E1 };


//this block had no input events


union ha_timerOutputEvents {
	struct {
		UDINT update;
	} event;
	
};


typedef struct {
    //input events
	

    //output events
	union ha_timerOutputEvents outputEvents;

    //input vars
	LREAL DeltaTime;
    
    //output vars
	LREAL x;
    
	//any internal vars (BFBs only)
    BOOL Variable1;
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum ha_timer_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	//this block uses cvode
	void *cvode_mem;
	N_Vector ode_solution;
	realtype T0;
	realtype Tnext;
	realtype Tcurr;
	int solveInProgress;
	

	
} ha_timer_t;

//all FBs get a preinit function
int ha_timer_preinit(ha_timer_t  *me);

//all FBs get an init function
int ha_timer_init(ha_timer_t  *me);

//all FBs get a run function
void ha_timer_run(ha_timer_t  *me);



#endif
