// This file is generated by FBC.

#ifndef CONVEYORCONTROLLER_H_
#define CONVEYORCONTROLLER_H_

#include "fbtypes.h"

typedef union {
    struct {
        UDINT InjectDone ; // 
        UDINT EmergencyStopChanged ; // 
        UDINT LasersChanged ; // 
    } event;
} ConveyorControllerIEvents;

typedef union {
    struct {
        UDINT ConveyorChanged ; // 
        UDINT ConveyorStoppedForInject ; // 
    } event;
} ConveyorControllerOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    ConveyorControllerIEvents _input;
    BOOL EmergencyStop; // 
    BOOL _EmergencyStop;
    BOOL InjectSiteLaser; // 
    BOOL _InjectSiteLaser;
    ConveyorControllerOEvents _output;
    BYTE ConveyorSpeed; // 
    BYTE _ConveyorSpeed;
    BOOL Variable1; // 
} ConveyorController;

/* Function block initialization function */
void ConveyorControllerinit(ConveyorController* me);

/* Function block execution function */
void ConveyorControllerrun(ConveyorController* me);

/* ECC algorithms */
void ConveyorController_ConveyorStart(ConveyorController* me);
void ConveyorController_ConveyorStop(ConveyorController* me);
void ConveyorController_ConveyorRunning(ConveyorController* me);
void ConveyorController_ConveyorEStop(ConveyorController* me);

#endif // CONVEYORCONTROLLER_H_
