// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Composite Function Block for _Core0
#include "_Core0.h"

//When running a composite block, note that you would call the functions in this order
//_init(); 
//do {
//_syncEvents();
//_syncData();
//_run();
//} loop;


/* _Core0_preinit() is required to be called to 
 * initialise an instance of _Core0. 
 * It sets all I/O values to zero.
 */
int _Core0_preinit(_Core0_t _SPM *me) {
	//if there are input events, reset them
	
	//if there are output events, reset them
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(ArgoRx_preinit(&me->rx) != 0) {
		return 1;
	}
	if(PrintInt_preinit(&me->print) != 0) {
		return 1;
	}
	
	
	//if this is a BFB, set _trigger to be true and start state so that the start state is properly executed
	

	return 0;
}

/* _Core0_init() is required to be called to 
 * set up an instance of _Core0. 
 * It passes around configuration data.
 */
int _Core0_init(_Core0_t _SPM *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	me->rx.ChanId = me->RxChanId;
	me->print.Data = me->rx.Data;
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(ArgoRx_init(&me->rx) != 0) {
		return 1;
	}
	if(PrintInt_init(&me->print) != 0) {
		return 1;
	}
	
	

	return 0;
}



/* _Core0_syncEvents() synchronises the events of an
 * instance of _Core0 as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core0_syncEvents(_Core0_t _SPM *me) {
	//for all composite function block children, call this same function
	
	//for all basic function block children, perform their synchronisations explicitly
	//events are always copied
	//inputs that go to children
	
	me->print.inputEvents.event.DataPresent = me->rx.outputEvents.event.DataPresent; 
	
	//outputs of parent cfb
	
	
}

/* _Core0_syncData() synchronises the data connections of an
 * instance of _Core0 as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core0_syncData(_Core0_t _SPM *me) {
	//for all composite function block children, call this same function
	
	//for all basic function block children, perform their synchronisations explicitly
	//Data is sometimes copied
	
	//sync for rx (of type ArgoRx) which is a BFB
	
	
	//sync for print (of type PrintInt) which is a BFB
	
	if(me->print.inputEvents.event.DataPresent == 1) { 
		me->print.Data = me->rx.Data;
	} 
	
	
	//for data that is sent from child to this CFB (me), always copy (event controlled copies will be resolved at the next level up)
	
	

}


/* _Core0_run() executes a single tick of an
 * instance of _Core0 according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void _Core0_run(_Core0_t _SPM *me) {
	ArgoRx_run(&me->rx);
	PrintInt_run(&me->print);
	
}

