// This file has been automatically generated by goFB and should not be edited by hand
// Transpiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Device Function Block for _TCREST
#include "_TCREST.h"

//When running a device block, note that you would call the functions in this order
//_init(); 
//do {
//_syncEvents();
//_syncData();
//_run();
//} loop;


/* _TCREST_init() is required to be called to 
 * initialise an instance of _TCREST. 
 * It sets all I/O values to zero.
 */
void _TCREST_init(struct _TCREST *me) {
	//if there are input events, reset them
	
	//if there are output events, reset them
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	me->Resource.Core0Input = 0;
	me->Resource1.Core1Input = 1;
	
	//if there are fb children (CFBs only), call this same function on them
	
	//if this is a BFB, set _trigger to be true and start state so that the start state is properly executed
	
}



/* _TCREST_syncEvents() synchronises the events of an
 * instance of _TCREST as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _TCREST_syncEvents(struct _TCREST *me) {
	//for all device function block resource function blocks, call this same function
	//resources are the only things that can be embedded in devices
	//sync for Resource (of type _Core0) which is a Resource
	_Core0_syncEvents(&me->Resource);//sync for Resource1 (of type _Core1) which is a Resource
	_Core1_syncEvents(&me->Resource1);
	
}

/* _TCREST_syncData() synchronises the data connections of an
 * instance of _TCREST as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _TCREST_syncData(struct _TCREST *me) {
	//for all device function block resource function blocks, call this same function
	//resources are the only things that can be embedded in devices
	//sync for Resource (of type _Core0) which is a Resource
	_Core0_syncData(&me->Resource);//sync for Resource1 (of type _Core1) which is a Resource
	_Core1_syncData(&me->Resource1);

}


/* _TCREST_run() executes a single tick of an
 * instance of _TCREST according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void _TCREST_run(struct _TCREST *me) {
	_Core0_run(&me->Resource);
	_Core1_run(&me->Resource1);
	
}

