// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block _TCREST
#ifndef _TCREST_H_
#define _TCREST_H_

#include "fbtypes.h"



//this block had no input events
//This block is a device and probably contains resources
#include "_Core0.h"
#include "_Core1.h"


//this block had no output events


typedef struct {
    //input events
	

    //output events
	

    //input vars
	
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	_Core0_t rx_core;
	_Core1_t tx_core;
	
	//state and trigger (BFBs only)
	
} _TCREST_t;

//all FBs get a preinit function
int _TCREST_preinit(_TCREST_t _SPM *me);

//all FBs get an init function
int _TCREST_init(_TCREST_t _SPM *me);

//all FBs get a run function
void _TCREST_run(_TCREST_t _SPM *me);

//composite/resource/device FBs get sync functions
void _TCREST_syncOutputEvents(_TCREST_t _SPM *me);
void _TCREST_syncInputEvents(_TCREST_t _SPM *me);

void _TCREST_syncOutputData(_TCREST_t _SPM *me);
void _TCREST_syncInputData(_TCREST_t _SPM *me);



#endif
