// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Basic Function Block for controller
#include "FB_controller.h"


/* controller_preinit() is required to be called to 
 * initialise an instance of controller. 
 * It sets all I/O values to zero.
 */
int controller_preinit(controller_t  *me) {
	//if there are input events, reset them
	me->inputEvents.event.update = 0;
	
	//if there are output events, reset them
	me->outputEvents.event.S2 = 0;
	me->outputEvents.event.S3 = 0;
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	me->_state = STATE_controller_Start;
	me->_trigger = true;
	
	
	

	return 0;
}

/* controller_init() is required to be called to 
 * set up an instance of controller. 
 * It passes around configuration data.
 */
int controller_init(controller_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//no algorithms were present for this function block


/* controller_run() executes a single tick of an
 * instance of controller according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 * Also note that on the first run of this function, trigger will be set
 * to true, meaning that on the very first run no next state logic will occur.
 */
void controller_run(controller_t  *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.S2 = 0;
	me->outputEvents.event.S3 = 0;
	

	//next state logic
	if(me->_trigger == false) {
		switch(me->_state) {
		case STATE_controller_Start:
			if(LREAL_EQ(me->x, 3) && LREAL_GTE(me->y, 6)) {
				me->_state = STATE_controller_State1;
				me->_trigger = true;
			} else if(LREAL_EQ(me->x, 3) && LREAL_LTE(me->y, 0)) {
				me->_state = STATE_controller_State2;
				me->_trigger = true;
			};
			break;
		case STATE_controller_State1:
			if(true) {
				me->_state = STATE_controller_Start;
				me->_trigger = true;
			};
			break;
		case STATE_controller_State2:
			if(true) {
				me->_state = STATE_controller_Start;
				me->_trigger = true;
			};
			break;
		
		}
	}

	//state output logic
	if(me->_trigger == true) {
		switch(me->_state) {
		case STATE_controller_Start:
			break;

		case STATE_controller_State1:
			me->outputEvents.event.S2 = 1;
			break;

		case STATE_controller_State2:
			me->outputEvents.event.S3 = 1;
			break;

		
		}
	}

	me->_trigger = false;
}


