// This file has NOT been automatically generated by goFB 
// Written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the Top of the IEC61499 network

module top_4

(
		input wire clk,
		
		//input events
		input wire InjectorArmFinishMovement_eI_1,
		input wire InjectorArmFinishMovement_eI_2,
		input wire InjectorArmFinishMovement_eI_3,
		input wire InjectorArmFinishMovement_eI_4,
		
		input wire EmergencyStopChanged_eI_1,
		input wire EmergencyStopChanged_eI_2,
		input wire EmergencyStopChanged_eI_3,
		input wire EmergencyStopChanged_eI_4,
		
		input wire CanisterPressureChanged_eI_1,
		input wire CanisterPressureChanged_eI_2,
		input wire CanisterPressureChanged_eI_3,
		input wire CanisterPressureChanged_eI_4,
		
		input wire FillContentsAvailableChanged_eI_1,
		input wire FillContentsAvailableChanged_eI_2,
		input wire FillContentsAvailableChanged_eI_3,
		input wire FillContentsAvailableChanged_eI_4,
		
		input wire LasersChanged_eI_1,
		input wire LasersChanged_eI_2,
		input wire LasersChanged_eI_3,
		input wire LasersChanged_eI_4,
		
		input wire DoorOverride_eI_1,
		input wire DoorOverride_eI_2,
		input wire DoorOverride_eI_3,
		input wire DoorOverride_eI_4,
		
		input wire VacuumTimerElapsed_eI_1,
		input wire VacuumTimerElapsed_eI_2,
		input wire VacuumTimerElapsed_eI_3,
		input wire VacuumTimerElapsed_eI_4,
		
		
		//output events
		output wire DoorReleaseCanister_eO_1,
		output wire DoorReleaseCanister_eO_2,
		output wire DoorReleaseCanister_eO_3,
		output wire DoorReleaseCanister_eO_4,
		
		output wire ConveyorChanged_eO_1,
		output wire ConveyorChanged_eO_2,
		output wire ConveyorChanged_eO_3,
		output wire ConveyorChanged_eO_4,
		
		output wire InjectorPositionChanged_eO_1,
		output wire InjectorPositionChanged_eO_2,
		output wire InjectorPositionChanged_eO_3,
		output wire InjectorPositionChanged_eO_4,
		
		output wire InjectorControlsChanged_eO_1,
		output wire InjectorControlsChanged_eO_2,
		output wire InjectorControlsChanged_eO_3,
		output wire InjectorControlsChanged_eO_4,
		
		output wire FillContentsChanged_eO_1,
		output wire FillContentsChanged_eO_2,
		output wire FillContentsChanged_eO_3,
		output wire FillContentsChanged_eO_4,
		
		output wire StartVacuumTimer_eO_1,
		output wire StartVacuumTimer_eO_2,
		output wire StartVacuumTimer_eO_3,
		output wire StartVacuumTimer_eO_4,
		
		output wire GoRejectArm_eO_1,
		output wire GoRejectArm_eO_2,
		output wire GoRejectArm_eO_3,
		output wire GoRejectArm_eO_4,
		
		output wire CanisterCountChanged_eO_1,
		output wire CanisterCountChanged_eO_2,
		output wire CanisterCountChanged_eO_3,
		output wire CanisterCountChanged_eO_4,
		
		output wire InjectDone_eO_1,
		output wire InjectDone_eO_2,
		output wire InjectDone_eO_3,
		output wire InjectDone_eO_4,
		
		
		//input variables
		input wire  EmergencyStop_I_1,
		input wire  EmergencyStop_I_2,
		input wire  EmergencyStop_I_3,
		input wire  EmergencyStop_I_4,
		
		input wire [7:0] CanisterPressure_I_1,
		input wire [7:0] CanisterPressure_I_2,
		input wire [7:0] CanisterPressure_I_3,
		input wire [7:0] CanisterPressure_I_4,
		
		input wire [7:0] FillContentsAvailable_I_1,
		input wire [7:0] FillContentsAvailable_I_2,
		input wire [7:0] FillContentsAvailable_I_3,
		input wire [7:0] FillContentsAvailable_I_4,
		
		input wire  DoorSiteLaser_I_1,
		input wire  DoorSiteLaser_I_2,
		input wire  DoorSiteLaser_I_3,
		input wire  DoorSiteLaser_I_4,
		
		input wire  InjectSiteLaser_I_1,
		input wire  InjectSiteLaser_I_2,
		input wire  InjectSiteLaser_I_3,
		input wire  InjectSiteLaser_I_4,
		
		input wire  RejectSiteLaser_I_1,
		input wire  RejectSiteLaser_I_2,
		input wire  RejectSiteLaser_I_3,
		input wire  RejectSiteLaser_I_4,
		
		input wire  RejectBinLaser_I_1,
		input wire  RejectBinLaser_I_2,
		input wire  RejectBinLaser_I_3,
		input wire  RejectBinLaser_I_4,
		
		input wire  AcceptBinLaser_I_1,
		input wire  AcceptBinLaser_I_2,
		input wire  AcceptBinLaser_I_3,
		input wire  AcceptBinLaser_I_4,
		
		
		//output variables
		output wire [7:0] ConveyorSpeed_O_1,
		output wire [7:0] ConveyorSpeed_O_2,
		output wire [7:0] ConveyorSpeed_O_3,
		output wire [7:0] ConveyorSpeed_O_4,
		
		output wire [7:0] InjectorPosition_O_1,
		output wire [7:0] InjectorPosition_O_2,
		output wire [7:0] InjectorPosition_O_3,
		output wire [7:0] InjectorPosition_O_4,
		
		output wire  InjectorContentsValveOpen_O_1,
		output wire  InjectorContentsValveOpen_O_2,
		output wire  InjectorContentsValveOpen_O_3,
		output wire  InjectorContentsValveOpen_O_4,
		
		output wire  InjectorVacuumRun_O_1,
		output wire  InjectorVacuumRun_O_2,
		output wire  InjectorVacuumRun_O_3,
		output wire  InjectorVacuumRun_O_4,
		
		output wire  InjectorPressurePumpRun_O_1,
		output wire  InjectorPressurePumpRun_O_2,
		output wire  InjectorPressurePumpRun_O_3,
		output wire  InjectorPressurePumpRun_O_4,
		
		output wire  FillContents_O_1,
		output wire  FillContents_O_2,
		output wire  FillContents_O_3,
		output wire  FillContents_O_4,
		
		output wire [7:0] CanisterCount_O_1,
		output wire [7:0] CanisterCount_O_2,
		output wire [7:0] CanisterCount_O_3,
		output wire [7:0] CanisterCount_O_4,
		
		

		input reset
);

// I/O
FB_FlexPRET t1(
	.clk(clk),
		
    //input events
    .InjectorArmFinishMovement_eI(InjectorArmFinishMovement_eI_1),
    .EmergencyStopChanged_eI(EmergencyStopChanged_eI_1),
    .CanisterPressureChanged_eI(CanisterPressureChanged_eI_1),
    .FillContentsAvailableChanged_eI(FillContentsAvailableChanged_eI_1),
    .LasersChanged_eI(LasersChanged_eI_1),
    .DoorOverride_eI(DoorOverride_eI_1),
    .VacuumTimerElapsed_eI(VacuumTimerElapsed_eI_1),
    
    //output events
    .DoorReleaseCanister_eO(DoorReleaseCanister_eO_1),
    .ConveyorChanged_eO(ConveyorChanged_eO_1),
    .InjectorPositionChanged_eO(InjectorPositionChanged_eO_1),
    .InjectorControlsChanged_eO(InjectorControlsChanged_eO_1),
    .FillContentsChanged_eO(FillContentsChanged_eO_1),
    .StartVacuumTimer_eO(StartVacuumTimer_eO_1),
    .GoRejectArm_eO(GoRejectArm_eO_1),
    .CanisterCountChanged_eO(CanisterCountChanged_eO_1),
    .InjectDone_eO(InjectDone_eO_1),
    
    //input variables
    .EmergencyStop_I(EmergencyStop_I_1),
    .CanisterPressure_I(CanisterPressure_I_1),
    .FillContentsAvailable_I(FillContentsAvailable_I_1),
    .DoorSiteLaser_I(DoorSiteLaser_I_1),
    .InjectSiteLaser_I(InjectSiteLaser_I_1),
    .RejectSiteLaser_I(RejectSiteLaser_I_1),
    .RejectBinLaser_I(RejectBinLaser_I_1),
    .AcceptBinLaser_I(AcceptBinLaser_I_1),
    
    //output variables
    .ConveyorSpeed_O(ConveyorSpeed_O_1),
    .InjectorPosition_O(InjectorPosition_O_1),
    .InjectorContentsValveOpen_O(InjectorContentsValveOpen_O_1),
    .InjectorVacuumRun_O(InjectorVacuumRun_O_1),
    .InjectorPressurePumpRun_O(InjectorPressurePumpRun_O_1),
    .FillContents_O(FillContents_O_1),
    .CanisterCount_O(CanisterCount_O_1),
    
	.reset(reset)
);

// I/O
FB_FlexPRET t2(
	.clk(clk),
		
    //input events
    .InjectorArmFinishMovement_eI(InjectorArmFinishMovement_eI_2),
    .EmergencyStopChanged_eI(EmergencyStopChanged_eI_2),
    .CanisterPressureChanged_eI(CanisterPressureChanged_eI_2),
    .FillContentsAvailableChanged_eI(FillContentsAvailableChanged_eI_2),
    .LasersChanged_eI(LasersChanged_eI_2),
    .DoorOverride_eI(DoorOverride_eI_2),
    .VacuumTimerElapsed_eI(VacuumTimerElapsed_eI_2),
    
    //output events
    .DoorReleaseCanister_eO(DoorReleaseCanister_eO_2),
    .ConveyorChanged_eO(ConveyorChanged_eO_2),
    .InjectorPositionChanged_eO(InjectorPositionChanged_eO_2),
    .InjectorControlsChanged_eO(InjectorControlsChanged_eO_2),
    .FillContentsChanged_eO(FillContentsChanged_eO_2),
    .StartVacuumTimer_eO(StartVacuumTimer_eO_2),
    .GoRejectArm_eO(GoRejectArm_eO_2),
    .CanisterCountChanged_eO(CanisterCountChanged_eO_2),
    .InjectDone_eO(InjectDone_eO_2),
    
    //input variables
    .EmergencyStop_I(EmergencyStop_I_2),
    .CanisterPressure_I(CanisterPressure_I_2),
    .FillContentsAvailable_I(FillContentsAvailable_I_2),
    .DoorSiteLaser_I(DoorSiteLaser_I_2),
    .InjectSiteLaser_I(InjectSiteLaser_I_2),
    .RejectSiteLaser_I(RejectSiteLaser_I_2),
    .RejectBinLaser_I(RejectBinLaser_I_2),
    .AcceptBinLaser_I(AcceptBinLaser_I_2),
    
    //output variables
    .ConveyorSpeed_O(ConveyorSpeed_O_2),
    .InjectorPosition_O(InjectorPosition_O_2),
    .InjectorContentsValveOpen_O(InjectorContentsValveOpen_O_2),
    .InjectorVacuumRun_O(InjectorVacuumRun_O_2),
    .InjectorPressurePumpRun_O(InjectorPressurePumpRun_O_2),
    .FillContents_O(FillContents_O_2),
    .CanisterCount_O(CanisterCount_O_2),
    
	.reset(reset)
);

// I/O
FB_FlexPRET t3(
	.clk(clk),
		
    //input events
    .InjectorArmFinishMovement_eI(InjectorArmFinishMovement_eI_3),
    .EmergencyStopChanged_eI(EmergencyStopChanged_eI_3),
    .CanisterPressureChanged_eI(CanisterPressureChanged_eI_3),
    .FillContentsAvailableChanged_eI(FillContentsAvailableChanged_eI_3),
    .LasersChanged_eI(LasersChanged_eI_3),
    .DoorOverride_eI(DoorOverride_eI_3),
    .VacuumTimerElapsed_eI(VacuumTimerElapsed_eI_3),
    
    //output events
    .DoorReleaseCanister_eO(DoorReleaseCanister_eO_3),
    .ConveyorChanged_eO(ConveyorChanged_eO_3),
    .InjectorPositionChanged_eO(InjectorPositionChanged_eO_3),
    .InjectorControlsChanged_eO(InjectorControlsChanged_eO_3),
    .FillContentsChanged_eO(FillContentsChanged_eO_3),
    .StartVacuumTimer_eO(StartVacuumTimer_eO_3),
    .GoRejectArm_eO(GoRejectArm_eO_3),
    .CanisterCountChanged_eO(CanisterCountChanged_eO_3),
    .InjectDone_eO(InjectDone_eO_3),
    
    //input variables
    .EmergencyStop_I(EmergencyStop_I_3),
    .CanisterPressure_I(CanisterPressure_I_3),
    .FillContentsAvailable_I(FillContentsAvailable_I_3),
    .DoorSiteLaser_I(DoorSiteLaser_I_3),
    .InjectSiteLaser_I(InjectSiteLaser_I_3),
    .RejectSiteLaser_I(RejectSiteLaser_I_3),
    .RejectBinLaser_I(RejectBinLaser_I_3),
    .AcceptBinLaser_I(AcceptBinLaser_I_3),
    
    //output variables
    .ConveyorSpeed_O(ConveyorSpeed_O_3),
    .InjectorPosition_O(InjectorPosition_O_3),
    .InjectorContentsValveOpen_O(InjectorContentsValveOpen_O_3),
    .InjectorVacuumRun_O(InjectorVacuumRun_O_3),
    .InjectorPressurePumpRun_O(InjectorPressurePumpRun_O_3),
    .FillContents_O(FillContents_O_3),
    .CanisterCount_O(CanisterCount_O_3),
    
	.reset(reset)
);

// I/O
FB_FlexPRET t4(
	.clk(clk),
		
    //input events
    .InjectorArmFinishMovement_eI(InjectorArmFinishMovement_eI_4),
    .EmergencyStopChanged_eI(EmergencyStopChanged_eI_4),
    .CanisterPressureChanged_eI(CanisterPressureChanged_eI_4),
    .FillContentsAvailableChanged_eI(FillContentsAvailableChanged_eI_4),
    .LasersChanged_eI(LasersChanged_eI_4),
    .DoorOverride_eI(DoorOverride_eI_4),
    .VacuumTimerElapsed_eI(VacuumTimerElapsed_eI_4),
    
    //output events
    .DoorReleaseCanister_eO(DoorReleaseCanister_eO_4),
    .ConveyorChanged_eO(ConveyorChanged_eO_4),
    .InjectorPositionChanged_eO(InjectorPositionChanged_eO_4),
    .InjectorControlsChanged_eO(InjectorControlsChanged_eO_4),
    .FillContentsChanged_eO(FillContentsChanged_eO_4),
    .StartVacuumTimer_eO(StartVacuumTimer_eO_4),
    .GoRejectArm_eO(GoRejectArm_eO_4),
    .CanisterCountChanged_eO(CanisterCountChanged_eO_4),
    .InjectDone_eO(InjectDone_eO_4),
    
    //input variables
    .EmergencyStop_I(EmergencyStop_I_4),
    .CanisterPressure_I(CanisterPressure_I_4),
    .FillContentsAvailable_I(FillContentsAvailable_I_4),
    .DoorSiteLaser_I(DoorSiteLaser_I_4),
    .InjectSiteLaser_I(InjectSiteLaser_I_4),
    .RejectSiteLaser_I(RejectSiteLaser_I_4),
    .RejectBinLaser_I(RejectBinLaser_I_4),
    .AcceptBinLaser_I(AcceptBinLaser_I_4),
    
    //output variables
    .ConveyorSpeed_O(ConveyorSpeed_O_4),
    .InjectorPosition_O(InjectorPosition_O_4),
    .InjectorContentsValveOpen_O(InjectorContentsValveOpen_O_4),
    .InjectorVacuumRun_O(InjectorVacuumRun_O_4),
    .InjectorPressurePumpRun_O(InjectorPressurePumpRun_O_4),
    .FillContents_O(FillContents_O_4),
    .CanisterCount_O(CanisterCount_O_4),
    
	.reset(reset)
);


endmodule