// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the ODE / Hybrid Automata Function Block for conveyorHFB
#include "FB_conveyorHFB.h"


/* conveyorHFB_preinit() is required to be called to 
 * initialise an instance of conveyorHFB. 
 * It sets all I/O values to zero.
 */
int conveyorHFB_preinit(conveyorHFB_t  *me) {
	//if there are input events, reset them
	me->inputEvents.event.Start = 0;
	me->inputEvents.event.Off = 0;
	me->inputEvents.event.On = 0;
	me->inputEvents.event.MChange = 0;
	
	//if there are output events, reset them
	me->outputEvents.event.XChange = 0;
	me->outputEvents.event.DChange = 0;
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	
	//if this is a BFB/odeFB, set start state so that the start state is properly executed and _trigger if necessary
	me->_state = STATE_conveyorHFB_Start;
	me->_trigger = true;
	
	me->cvode_mem = NULL;
	me->Tcurr = 0;
	me->Tnext = 0;
	me->T0 = 0;
	me->solveInProgress = 0;
	
	
	return 0;
}

/* conveyorHFB_init() is required to be called to 
 * set up an instance of conveyorHFB. 
 * It passes around configuration data.
 */
int conveyorHFB_init(conveyorHFB_t  *me) {
	//pass in any parameters on this level
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	
	

	return 0;
}



//algorithms


static int conveyorHFB_QoffAlg_ode_f(realtype t, N_Vector ode_solution, N_Vector ode_solution_dot, void *user_data) {
	//AUTOGENERATED CODE: this function represents the ODE in conveyorHFB's QoffAlg algorithm
	//it is in a format that CVODE can process.
	conveyorHFB_t *me = (conveyorHFB_t*)user_data;
	
	NV_Ith_S(ode_solution_dot, 0) = -2 * NV_Ith_S(ode_solution, 0);
	
	return 0;
}

static int conveyorHFB_QoffAlg_ode_g(realtype t, N_Vector ode_solution, realtype *gout, void *user_data) {
	//AUTOGENERATED CODE: this function represents the roots of the ODE in conveyorHFB's QoffAlg algorithm
	//it is in a format that CVODE can process.
	
	gout[0] = NV_Ith_S(ode_solution, 0) - (0);
	
	return 0;
}

//return 1 if we found a root
int conveyorHFB_QoffAlg(conveyorHFB_t *me) {
	//AUTOGENERATED CODE: this function manages iterations of the ODE in conveyorHFB's QoffAlg algorithm
	//It calls the CVODE solver and sets the outputs of the HA FB.
	if(me->solveInProgress == 0) {
		me->Tnext += me->DeltaTime;
		me->solveInProgress = 1; //solveInProgress is used to mark if we are currently solving
	}
	int flag = CVode(me->cvode_mem, me->Tnext, me->ode_solution, &me->Tcurr, CV_NORMAL);
	if (flag < 0) {
		fprintf(stderr, "Error in CVode: %d\n", flag);
		while(1);
	} 
	
	
	me->X = NV_Ith_S(me->ode_solution, 0);
	
	me->D = me->D + me->X;
	

	if(flag == CV_ROOT_RETURN) {
		return 1;
	}

	me->solveInProgress = 0;
	return 0;
}




static int conveyorHFB_QonAlg_ode_f(realtype t, N_Vector ode_solution, N_Vector ode_solution_dot, void *user_data) {
	//AUTOGENERATED CODE: this function represents the ODE in conveyorHFB's QonAlg algorithm
	//it is in a format that CVODE can process.
	conveyorHFB_t *me = (conveyorHFB_t*)user_data;
	
	NV_Ith_S(ode_solution_dot, 0) = (1 - NV_Ith_S(ode_solution, 0));
	
	return 0;
}

static int conveyorHFB_QonAlg_ode_g(realtype t, N_Vector ode_solution, realtype *gout, void *user_data) {
	//AUTOGENERATED CODE: this function represents the roots of the ODE in conveyorHFB's QonAlg algorithm
	//it is in a format that CVODE can process.
	
	gout[0] = NV_Ith_S(ode_solution, 0) - (0);
	
	return 0;
}

//return 1 if we found a root
int conveyorHFB_QonAlg(conveyorHFB_t *me) {
	//AUTOGENERATED CODE: this function manages iterations of the ODE in conveyorHFB's QonAlg algorithm
	//It calls the CVODE solver and sets the outputs of the HA FB.
	if(me->solveInProgress == 0) {
		me->Tnext += me->DeltaTime;
		me->solveInProgress = 1; //solveInProgress is used to mark if we are currently solving
	}
	int flag = CVode(me->cvode_mem, me->Tnext, me->ode_solution, &me->Tcurr, CV_NORMAL);
	if (flag < 0) {
		fprintf(stderr, "Error in CVode: %d\n", flag);
		while(1);
	} 
	
	
	me->X = NV_Ith_S(me->ode_solution, 0);
	
	me->D = me->D + me->X;
	

	if(flag == CV_ROOT_RETURN) {
		return 1;
	}

	me->solveInProgress = 0;
	return 0;
}




void conveyorHFB_xPrimeEqZeroAlg(conveyorHFB_t *me, CVRhsFn ode_f, CVRootFn ode_g) {
	//AUTOGENERATED CODE: this algorithm specifies the initialization of a CVODE SUNDIALS solver and was parsed from the algorithm's text field
	int flag;
	

	//free solver if it is initialized
	if(me->cvode_mem != NULL) {
		CVodeFree(&me->cvode_mem);
		N_VDestroy_Serial(me->ode_solution);  /* Free y vector */
	}

	//create solver
	me->ode_solution = N_VNew_Serial(1); //length of initial values
	me->cvode_mem = CVodeCreate(CV_ADAMS, CV_FUNCTIONAL);
	if (me->cvode_mem == 0) {
		fprintf(stderr, "Error in CVodeMalloc: could not allocate\n");
		while(1);
	}

	//specify initial values
	
	NV_Ith_S(me->ode_solution, 0) = 0;
	
		
	me->T0 = me->Tcurr; //set T0 to whatever real time we were counting from before
	
	if(me->solveInProgress == 0) { //only reset Tnext if we aren't currently solving (sometimes we might be taking a mid-tick transition)
		me->Tnext = me->Tcurr;
	}

	//initialize solver with pointer to values
	flag = CVodeInit(me->cvode_mem, ode_f, me->T0, me->ode_solution);
    if (flag < 0) {
		fprintf(stderr, "Error in CVodeMalloc: %d\n", flag);
		while(1);
    }

	flag = CVodeSetUserData(me->cvode_mem, me);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeSetUserData: %d\n", flag);
		while(1);
    }


	//set solver tolerances
	flag = CVodeSStolerances(me->cvode_mem, REL_TOL, ABS_TOL);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeSStolerances: %d\n", flag);
		while(1);
	}

	//set root function
	flag = CVodeRootInit(me->cvode_mem, 1, ode_g);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeRootInit: %d\n", flag);
		while(1);
	}
}



void conveyorHFB_xPrimeEqXAlg(conveyorHFB_t *me, CVRhsFn ode_f, CVRootFn ode_g) {
	//AUTOGENERATED CODE: this algorithm specifies the initialization of a CVODE SUNDIALS solver and was parsed from the algorithm's text field
	int flag;
	

	//free solver if it is initialized
	if(me->cvode_mem != NULL) {
		CVodeFree(&me->cvode_mem);
		N_VDestroy_Serial(me->ode_solution);  /* Free y vector */
	}

	//create solver
	me->ode_solution = N_VNew_Serial(1); //length of initial values
	me->cvode_mem = CVodeCreate(CV_ADAMS, CV_FUNCTIONAL);
	if (me->cvode_mem == 0) {
		fprintf(stderr, "Error in CVodeMalloc: could not allocate\n");
		while(1);
	}

	//specify initial values
	
	NV_Ith_S(me->ode_solution, 0) = me->X;
	
		
	me->T0 = me->Tcurr; //set T0 to whatever real time we were counting from before
	
	if(me->solveInProgress == 0) { //only reset Tnext if we aren't currently solving (sometimes we might be taking a mid-tick transition)
		me->Tnext = me->Tcurr;
	}

	//initialize solver with pointer to values
	flag = CVodeInit(me->cvode_mem, ode_f, me->T0, me->ode_solution);
    if (flag < 0) {
		fprintf(stderr, "Error in CVodeMalloc: %d\n", flag);
		while(1);
    }

	flag = CVodeSetUserData(me->cvode_mem, me);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeSetUserData: %d\n", flag);
		while(1);
    }


	//set solver tolerances
	flag = CVodeSStolerances(me->cvode_mem, REL_TOL, ABS_TOL);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeSStolerances: %d\n", flag);
		while(1);
	}

	//set root function
	flag = CVodeRootInit(me->cvode_mem, 1, ode_g);
	if (flag < 0) {
		fprintf(stderr, "Error in CVodeRootInit: %d\n", flag);
		while(1);
	}
}




/* conveyorHFB_run() executes a single tick of an
 * instance of conveyorHFB according to synchronous semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * will need to be done in the parent.
 * Also note that on the first run of this function, trigger will be set
 * to true, meaning that on the very first run no next state logic will occur.
 */
void conveyorHFB_run(conveyorHFB_t *me) {
	//if there are output events, reset them
	
	me->outputEvents.event.XChange = 0;
	me->outputEvents.event.DChange = 0;
	

	int odeRootFound; //used to trigger mid-tick transitions

restart:	//ode ECCs have ode setup states that aren't maintained for a tick, 
			//so they are passed through, so they need a place to goto 

repeat: 	//when we have had a mid-tick transition, we want to start the run again 
			
	me->_trigger = false;


	//next state logic
	if(me->_trigger == false) {
		switch(me->_state) {
		case STATE_conveyorHFB_Start:
			if(me->inputEvents.event.Start) {
				
				if(me->inputEvents.event.Start) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.Start = 0;
				}
				me->_state = STATE_conveyorHFB_enterQoff0;
				me->_trigger = true;
			};
			break;
		case STATE_conveyorHFB_Qoff:
			if(me->inputEvents.event.On) {
				
				if(me->inputEvents.event.On) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.On = 0;
				}
				me->_state = STATE_conveyorHFB_enterQon0;
				me->_trigger = true;
			} else if(0 <= me->X && me->X <= me->M) {
				
				me->_state = STATE_conveyorHFB_Qoff;
				me->_trigger = true;
			};
			break;
		case STATE_conveyorHFB_Qon:
			if(me->inputEvents.event.Off) {
				
				if(me->inputEvents.event.Off) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.Off = 0;
				}
				me->_state = STATE_conveyorHFB_enterQoff1;
				me->_trigger = true;
			} else if(0 <= me->X && me->X <= me->M) {
				
				me->_state = STATE_conveyorHFB_Qon;
				me->_trigger = true;
			};
			break;
		case STATE_conveyorHFB_enterQon0:
			if(me->inputEvents.event.Off) {
				
				if(me->inputEvents.event.Off) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.Off = 0;
				}
				me->_state = STATE_conveyorHFB_enterQoff1;
				me->_trigger = true;
			} else if(0 <= me->X && me->X <= me->M) {
				
				me->_state = STATE_conveyorHFB_Qon;
				me->_trigger = true;
			};
			break;
		case STATE_conveyorHFB_enterQoff0:
			if(me->inputEvents.event.On) {
				
				if(me->inputEvents.event.On) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.On = 0;
				}
				me->_state = STATE_conveyorHFB_enterQon0;
				me->_trigger = true;
			} else if(0 <= me->X && me->X <= me->M) {
				
				me->_state = STATE_conveyorHFB_Qoff;
				me->_trigger = true;
			};
			break;
		case STATE_conveyorHFB_enterQoff1:
			if(me->inputEvents.event.On) {
				
				if(me->inputEvents.event.On) { //events should cause no more than one transition, so due to possible mid-tick transitions in odeFBs we should consume events after we read them
					me->inputEvents.event.On = 0;
				}
				me->_state = STATE_conveyorHFB_enterQon0;
				me->_trigger = true;
			} else if(0 <= me->X && me->X <= me->M) {
				
				me->_state = STATE_conveyorHFB_Qoff;
				me->_trigger = true;
			};
			break;
		
		}
	}
	
	odeRootFound = 0;

	if(me->_trigger == true) {
		switch(me->_state) {
		case STATE_conveyorHFB_Start:
			
			if(odeRootFound == 1) {
				me->solveInProgress=0;me->Tcurr = me->Tnext;
			}
			break;
		case STATE_conveyorHFB_Qoff:
			
			odeRootFound = conveyorHFB_QoffAlg(me);
			me->outputEvents.event.XChange = 1;
			
			me->outputEvents.event.DChange = 1;
			
			if(odeRootFound == 1) {
				me->solveInProgress=0;me->Tcurr = me->Tnext;
			}
			break;
		case STATE_conveyorHFB_Qon:
			
			odeRootFound = conveyorHFB_QonAlg(me);
			me->outputEvents.event.XChange = 1;
			
			me->outputEvents.event.DChange = 1;
			
			if(odeRootFound == 1) {
				me->solveInProgress=0;me->Tcurr = me->Tnext;
			}
			break;
		case STATE_conveyorHFB_enterQon0:
			
			//init all ode algorithms that this state feeds into
			conveyorHFB_xPrimeEqXAlg(me, conveyorHFB_QonAlg_ode_f, conveyorHFB_QonAlg_ode_g);
			me->outputEvents.event.XChange = 1;
			
			odeRootFound = conveyorHFB_QonAlg(me);
			me->outputEvents.event.DChange = 1;
			
			//this is an ODE setup state (ODE_init) so we need to repeat this whole function body
			/*goto restart; this is currently disabled because we don't need it when running non-optimised versions of code*/
			break;
		case STATE_conveyorHFB_enterQoff0:
			
			//init all ode algorithms that this state feeds into
			conveyorHFB_xPrimeEqZeroAlg(me, conveyorHFB_QoffAlg_ode_f, conveyorHFB_QoffAlg_ode_g);
			me->outputEvents.event.XChange = 1;
			
			odeRootFound = conveyorHFB_QoffAlg(me);
			me->outputEvents.event.DChange = 1;
			
			//this is an ODE setup state (ODE_init) so we need to repeat this whole function body
			/*goto restart; this is currently disabled because we don't need it when running non-optimised versions of code*/
			break;
		case STATE_conveyorHFB_enterQoff1:
			
			//init all ode algorithms that this state feeds into
			conveyorHFB_xPrimeEqXAlg(me, conveyorHFB_QoffAlg_ode_f, conveyorHFB_QoffAlg_ode_g);
			me->outputEvents.event.XChange = 1;
			
			odeRootFound = conveyorHFB_QoffAlg(me);
			me->outputEvents.event.DChange = 1;
			
			//this is an ODE setup state (ODE_init) so we need to repeat this whole function body
			/*goto restart; this is currently disabled because we don't need it when running non-optimised versions of code*/
			break;
		
		}
	}
	
	printf("[%i]: %f,%f,%f\t", me->_state, me->Tcurr, me->D, me->X);

}


