// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block oven
#ifndef OVEN_H_
#define OVEN_H_

#include "fbtypes.h"
#include "util.h"


#include "cvode/cvode.h"
#include "nvector/nvector_serial.h"
#include "cvode/cvode_dense.h"
#include "sundials/sundials_dense.h"
#include "sundials/sundials_types.h"


//This is a BFB, so we need an enum type for the state machine
enum oven_states { STATE_oven_Start, STATE_oven_frozenE0, STATE_oven_frozen, STATE_oven_cookE0, STATE_oven_cook, STATE_oven_burnE0, STATE_oven_burn, STATE_oven_coolE0, STATE_oven_coolE1, STATE_oven_cool, STATE_oven_frozenE1 };


union ovenInputEvents {
	struct {
		UDINT start;
		UDINT remove;
		UDINT done;
	} event;
	
};


union ovenOutputEvents {
	struct {
		UDINT xChange;
		UDINT Smoke;
	} event;
	
};


typedef struct {
    //input events
	union ovenInputEvents inputEvents;

    //output events
	union ovenOutputEvents outputEvents;

    //input vars
	LREAL DeltaTime;
    
    //output vars
	LREAL x;
    
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum oven_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	//this block uses cvode
	void *cvode_mem;
	N_Vector ode_solution;
	realtype T0;
	realtype Tnext;
	realtype Tcurr;
	int solveInProgress;
	

	
} oven_t;

//all FBs get a preinit function
int oven_preinit(oven_t  *me);

//all FBs get an init function
int oven_init(oven_t  *me);

//all FBs get a run function
void oven_run(oven_t  *me);



#endif
