// This file is generated by FBC.

#include "PendingRequestGenerator.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void PendingRequestGeneratorinit(PendingRequestGenerator* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void PendingRequestGenerator_UpdateCallValues(PendingRequestGenerator* me)
{
int i = 0;
//update PendingCabinCall
if (me->_input.event.CabinCall) {
 for (i = 0; i < 4; ++i) {
  me->PendingCabinCallValue[i] |= me->CabinCallValue[i];
 }
}
if (me->_input.event.StoppedAtFloor) {
 me->PendingCabinCallValue[me->StoppedAtFloorValue] = 0;
}
//update PendingUpCall
int hasUpRequests = 0;
if (me->_input.event.UpCall) {
 for (i = 0; i < 4; ++i) {
  me->PendingUpCallValue[i] |= me->UpCallValue[i];
  hasUpRequests|= me->UpCallValue[i];
 }
}
//update PendingDownCall
int hasDownRequests = 0;
if (me->_input.event.DownCall) {
 for (i = 0; i < 4; ++i) {
  me->PendingDownCallValue[i] |= me->DownCallValue[i];
  hasDownRequests |= me->DownCallValue[i];
 }
}
if ((me->_input.event.StoppedAtFloor&&me->preMotorDirectionUp) || (hasDownRequests==0)) {
 me->PendingUpCallValue[me->StoppedAtFloorValue] = 0;
}
if ((me->_input.event.StoppedAtFloor&&me->preMotorDirectionDown) || (hasUpRequests==0)) {
 me->PendingDownCallValue[me->StoppedAtFloorValue] = 0;
}
me->preCallRequest = 0;
//update PendingCall
for (i = 0; i < 4; ++i) {
    me->PendingCallValue[i] |=  me->PendingCabinCallValue[i] ||  me->PendingUpCallValue[i] || me->PendingDownCallValue[i];
 me->preCallRequest |= me->PendingCallValue[i];
}
if (me->_input.event.StoppedAtFloor) {
 me->PendingCallValue[me->StoppedAtFloorValue] = 0;
}
//update PendingReq
for (i = 0; i < 4; ++i) {
    me->PendingReqValue[i] = me->PendingCallValue[i];
}
me->preMotorDirectionUp = me->_input.event.MotorDirectionUp;
me->preMotorDirectionDown = me->_input.event.MotorDirectionDown;


}

/* Function block execution function */
void PendingRequestGeneratorrun(PendingRequestGenerator* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.CabinCall) {
            {
                int i;
                for (i = 0; i < 4; i++) {
                    me->CabinCallValue[i] = me->_CabinCallValue[i];
                }
            }
        }
        if (me->_input.event.UpCall) {
            {
                int i;
                for (i = 0; i < 4; i++) {
                    me->UpCallValue[i] = me->_UpCallValue[i];
                }
            }
        }
        if (me->_input.event.DownCall) {
            {
                int i;
                for (i = 0; i < 4; i++) {
                    me->DownCallValue[i] = me->_DownCallValue[i];
                }
            }
        }
        if (me->_input.event.StoppedAtFloor) {
            me->StoppedAtFloorValue = me->_StoppedAtFloorValue;
        }
    }
    for (;;) {
        if (me->_state == 0) {
            // State: Start
            if (!me->_entered) {
                PendingRequestGenerator_UpdateCallValues(me);
                me->_output.event.PendingCabinCall = 1;
                me->_output.event.PendingUpCall = 1;
                me->_output.event.PendingDownCall = 1;
                me->_output.event.PendingCall = 1;
                me->_entered = true;
            }
            else {
                if (me->preCallRequest == true) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
                else {
                    me->_state = 0;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: PendingReq
            if (!me->_entered) {
                PendingRequestGenerator_UpdateCallValues(me);
                me->_output.event.PendingReq = 1;
                me->_output.event.PendingCabinCall = 1;
                me->_output.event.PendingUpCall = 1;
                me->_output.event.PendingDownCall = 1;
                me->_output.event.PendingCall = 1;
                me->_entered = true;
            }
            else {
                if (me->preCallRequest == false) {
                    me->_state = 0;
                    me->_entered = false;
                    continue;
                }
                else {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        break;
    }
    if (me->_output.event.PendingCabinCall) {
        {
            int i;
            for (i = 0; i < 4; i++) {
                me->_PendingCabinCallValue[i] = me->PendingCabinCallValue[i];
            }
        }
    }
    if (me->_output.event.PendingUpCall) {
        {
            int i;
            for (i = 0; i < 4; i++) {
                me->_PendingUpCallValue[i] = me->PendingUpCallValue[i];
            }
        }
    }
    if (me->_output.event.PendingDownCall) {
        {
            int i;
            for (i = 0; i < 4; i++) {
                me->_PendingDownCallValue[i] = me->PendingDownCallValue[i];
            }
        }
    }
    if (me->_output.event.PendingCall) {
        {
            int i;
            for (i = 0; i < 4; i++) {
                me->_PendingCallValue[i] = me->PendingCallValue[i];
            }
        }
    }
    if (me->_output.event.PendingReq) {
        {
            int i;
            for (i = 0; i < 4; i++) {
                me->_PendingReqValue[i] = me->PendingReqValue[i];
            }
        }
    }

    me->_input.events = 0;
}

