// This file is generated by FBC.

#include "RequestConsumer.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void RequestConsumerinit(RequestConsumer* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void RequestConsumer_UpdateRequest(RequestConsumer* me)
{
me->requestValue = me->CurrentPriorityValue;
}

/* Function block execution function */
void RequestConsumerrun(RequestConsumer* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.CurrentPriority) {
            me->CurrentPriorityValue = me->_CurrentPriorityValue;
        }
        if (me->_input.event.StoppedAtFloor) {
            me->StoppedAtFloorValue = me->_StoppedAtFloorValue;
        }
    }
    for (;;) {
        if (me->_state == 0) {
            // State: FloorHasHighestPriority
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                if (me->_input.event.CurrentPriority && (me->CurrentPriorityValue != me->StoppedAtFloorValue)) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: FloorHasNotHighestPriority
            if (!me->_entered) {
                RequestConsumer_UpdateRequest(me);
                me->_output.event.request = 1;
                me->_entered = true;
            }
            else {
                if (me->_input.event.StoppedAtFloor && (me->CurrentPriorityValue == me->StoppedAtFloorValue)) {
                    me->_state = 0;
                    me->_entered = false;
                    continue;
                }
                else {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        break;
    }
    if (me->_output.event.request) {
        me->_requestValue = me->requestValue;
    }

    me->_input.events = 0;
}

