// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block SifbCBPrintStatus
#ifndef SIFBCBPRINTSTATUS_H_
#define SIFBCBPRINTSTATUS_H_

#include "fbtypes.h"
#include "util.h"



//This is a BFB with states, so we need an enum type for the state machine
enum SifbCBPrintStatus_states { STATE_SifbCBPrintStatus_Start, STATE_SifbCBPrintStatus_Update };




union SifbCBPrintStatusInputEvents {
	struct {
		UDINT StatusUpdate;
	} event;
	
};


//this block had no output events


typedef struct {
    //input events
	union SifbCBPrintStatusInputEvents inputEvents;

    //output events
	

    //input vars
	INT St1;
    INT St2;
    INT St3;
    
    //output vars
	
	//any internal vars (BFBs only)
    BOOL Variable1;
    
	//any child FBs (CFBs only)
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	enum SifbCBPrintStatus_states _state; //stores current state
	BOOL _trigger; //indicates if a state transition has occured this tick
	
	
	

	

} SifbCBPrintStatus_t;

//all FBs get a preinit function
int SifbCBPrintStatus_preinit(SifbCBPrintStatus_t  *me);

//all FBs get an init function
int SifbCBPrintStatus_init(SifbCBPrintStatus_t  *me);

//all FBs get a run function
void SifbCBPrintStatus_run(SifbCBPrintStatus_t  *me);



#endif
