// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB
// Verilog support is EXPERIMENTAL ONLY

// This file represents the Top of the IEC61499 network

module top 

(
		input wire clk,
		
		//input events
		input wire tick_eI,
		input wire i_measured_eI,
		input wire test_eI,
		input wire set_eI,
		input wire iSet_change_eI,
		
		//output events
		output wire b_change_eO,
		
		//input variables
		input wire unsigned [7:0] i_I,
		input wire unsigned [7:0] iSet_I,
		
		//output variables
		output wire  b_O ,
		

		input reset
);


// I/O
FB_CfbOvercurrentDetector iec61499_network_top (
	.clk(clk),
		
    //input events
    .tick_eI(tick_eI),
    .i_measured_eI(i_measured_eI),
    .test_eI(test_eI),
    .set_eI(set_eI),
    .iSet_change_eI(iSet_change_eI),
    
    //output events
    .b_change_eO(b_change_eO),
    
    //input variables
    .i_I(i_I),
    .iSet_I(iSet_I),
    
    //output variables
    .b_O(b_O),
    
	.reset(reset)
);


endmodule