// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block FakePacemakerTop
#ifndef FAKEPACEMAKERTOP_H_
#define FAKEPACEMAKERTOP_H_

#include "fbtypes.h"

//This is a CFB, so we need the #includes for the child blocks embedded here
#include "VVI_Pacemaker.h"


//this block had no input events


//this block had no output events


typedef struct {
    //input events
	

    //output events
	

    //input vars
	
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	VVI_Pacemaker_t pmaker;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
} FakePacemakerTop_t;

//all FBs get a preinit function
int FakePacemakerTop_preinit(FakePacemakerTop_t  *me);

//all FBs get an init function
int FakePacemakerTop_init(FakePacemakerTop_t  *me);

//all FBs get a run function
void FakePacemakerTop_run(FakePacemakerTop_t  *me);

//composite/resource/device FBs get sync functions
void FakePacemakerTop_syncOutputEvents(FakePacemakerTop_t  *me);
void FakePacemakerTop_syncInputEvents(FakePacemakerTop_t  *me);

void FakePacemakerTop_syncOutputData(FakePacemakerTop_t  *me);
void FakePacemakerTop_syncInputData(FakePacemakerTop_t  *me);



#endif
