// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the interface of Function Block _Core
#ifndef _CORE_H_
#define _CORE_H_

#include "fbtypes.h"

//This is a CFB, so we need the #includes for the child blocks embedded here
#include "PID.h"
#include "Manager.h"
#include "Plant.h"


//this block had no input events


//this block had no output events


typedef struct {
    //input events
	

    //output events
	

    //input vars
	
    //output vars
	
	//any internal vars (BFBs only)
    
	//any child FBs (CFBs only)
	PID_t pid;
	Manager_t manager;
	Plant_t plant;
	
	//resource vars
	
	//resources (Devices only)
	
	//state and trigger (BFBs only)
	
} _Core_t;

//all FBs get a preinit function
int _Core_preinit(_Core_t _SPM *me);

//all FBs get an init function
int _Core_init(_Core_t _SPM *me);

//all FBs get a run function
void _Core_run(_Core_t _SPM *me);

//composite/resource/device FBs get sync functions
void _Core_syncOutputEvents(_Core_t _SPM *me);
void _Core_syncInputEvents(_Core_t _SPM *me);

void _Core_syncOutputData(_Core_t _SPM *me);
void _Core_syncInputData(_Core_t _SPM *me);



#endif
