// This file has been automatically generated by goFB and should not be edited by hand
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB

// This file represents the implementation of the Composite Function Block for _Core
#include "_Core.h"

//When running a composite block, note that you would call the functions in this order (and this is very important)
//_preinit(); 
//_init();
//do {
//	_syncOutputEvents();
//	_syncInputEvents();
//	_syncOutputData();
//	_syncInputData();
//	_run();
//} loop;


/* _Core_preinit() is required to be called to 
 * initialise an instance of _Core. 
 * It sets all I/O values to zero.
 */
int _Core_preinit(_Core_t _SPM *me) {
	//if there are input events, reset them
	
	//if there are output events, reset them
	
	//if there are input vars with default values, set them
	
	//if there are output vars with default values, set them
	
	//if there are internal vars with default values, set them (BFBs only)
	
	//if there are resource vars with default values, set them
	
	//if there are resources with set parameters, set them
	
	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(PID_preinit(&me->pid) != 0) {
		return 1;
	}
	if(Manager_preinit(&me->manager) != 0) {
		return 1;
	}
	if(Plant_preinit(&me->plant) != 0) {
		return 1;
	}
	
	
	//if this is a BFB, set _trigger to be true and start state so that the start state is properly executed
	

	return 0;
}

/* _Core_init() is required to be called to 
 * set up an instance of _Core. 
 * It passes around configuration data.
 */
int _Core_init(_Core_t _SPM *me) {
	//pass in any parameters on this level
	me->pid.PGain = 0.4;
	me->pid.IGain = 0.05;
	me->pid.DGain = 0.5;
	me->pid.WindupGuard = 1.0;
	me->manager.TicksPerVal = 100;
	
	
	

	//perform a data copy to all children (if any present) (can move config data around, doesn't do anything otherwise)
	me->plant.Control = me->pid.Control;
	me->pid.DesiredValue = me->manager.DesiredValue;
	me->pid.ActualValue = me->plant.Value;
	me->manager.ActualValue = me->plant.Value;
	

	//if there are fb children (CFBs/Devices/Resources only), call this same function on them
	if(PID_init(&me->pid) != 0) {
		return 1;
	}
	if(Manager_init(&me->manager) != 0) {
		return 1;
	}
	if(Plant_init(&me->plant) != 0) {
		return 1;
	}
	
	

	return 0;
}



/* _Core_syncOutputEvents() synchronises the output events of an
 * instance of _Core as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core_syncOutputEvents(_Core_t _SPM *me) {
	//first, for all cfb children, call this same function
	
	Plant_syncOutputEvents(&me->plant);//sync for plant (of type Plant) which is a CFB
	
	
	//then, for all connections that are connected to an output on the parent, run their run their copy
	
}

/* _Core_syncInputEvents() synchronises the input events of an
 * instance of _Core as required by synchronous semantics.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core_syncInputEvents(_Core_t _SPM *me) {
	//first, we explicitly synchronise the children
	
	me->pid.inputEvents.event.Zero = me->manager.outputEvents.event.Zero; 
	
	me->pid.inputEvents.event.Tick = me->manager.outputEvents.event.Tick; 
	
	me->pid.inputEvents.event.ActualValueChanged = me->plant.outputEvents.event.ValueChange; 
	
	me->manager.inputEvents.event.ActualValueChanged = me->plant.outputEvents.event.ValueChange; 
	
	me->plant.inputEvents.event.Zero = me->manager.outputEvents.event.Zero; 
	
	me->plant.inputEvents.event.ControlChange = me->pid.outputEvents.event.ControlChanged; 
	

	//then, call this same function on all cfb children
	
	Plant_syncInputEvents(&me->plant);//sync for plant (of type Plant) which is a CFB
	
}

/* _Core_syncOutputData() synchronises the output data connections of an
 * instance of _Core as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core_syncOutputData(_Core_t _SPM *me) {
	//for all composite function block children, call this same function
	//sync for plant (of type Plant) which is a CFB
	Plant_syncOutputData(&me->plant);
	
	//for data that is sent from child to this CFB (me), always copy (event controlled copies will be resolved at the next level up) //TODO: arrays!?
	
	
}

/* _Core_syncInputData() synchronises the input data connections of an
 * instance of _Core as required by synchronous semantics.
 * It does the checking to ensure that only connections which have had their
 * associated event fire are updated.
 * Notice that it does NOT perform any computation - this occurs in the
 * _run function.
 */
void _Core_syncInputData(_Core_t _SPM *me) {
	//for all basic function block children, perform their synchronisations explicitly
	
	//sync for pid (of type PID) which is a BFB
	
	if(me->pid.inputEvents.event.Zero == 1) { 
	} 
	if(me->pid.inputEvents.event.Tick == 1) { 
		me->pid.DesiredValue = me->manager.DesiredValue;
	} 
	if(me->pid.inputEvents.event.ActualValueChanged == 1) { 
		me->pid.ActualValue = me->plant.Value;
	} 
	
	//sync for manager (of type Manager) which is a BFB
	
	if(me->manager.inputEvents.event.ActualValueChanged == 1) { 
		me->manager.ActualValue = me->plant.Value;
	} 
	//sync for plant (of Type Plant) which is a CFB
	
	
		me->plant.Control = me->pid.Control;
	
	
	//for all composite function block children, call this same function
	//sync for plant (of type Plant) which is a CFB
	Plant_syncInputData(&me->plant);
	
}


/* _Core_run() executes a single tick of an
 * instance of _Core according to synchronise semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the _syncX functions at this (and any higher) level.
 */
void _Core_run(_Core_t _SPM *me) {
	PID_run(&me->pid);
	Manager_run(&me->manager);
	Plant_run(&me->plant);
	
}

